### ISSUE TITLE
move semantics

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#190]
Let's say we have a non-copyable List data structure (current implementation in std matches this because of the `prealloc_data` field).

``` zig
// non-copyable
struct List { ... }

struct Buffer {
    data: List(u8),
}

struct Token {
    name: Buffer,
}

struct CompletedTokenization {
    tokens: List(Token),
}
```

`List(Token)` is (not currently but should be) a compile error because the list implementation calls `realloc` on `T` which copies the data. And `List` itself is non-copyable, so that bubbles up and means you can't have `tokens: List(Token)`.
1. Make this a compile error.
2. Should we specify move semantics so that this can actually be allowed and work correctly?

**Comment by aindigo** [comment]
may be not related but: any plans to make object lifetimes accesible in some way to templates so they can be compared at compile time? (ie, if an object can outlive me ('a<'b) i can not share a resource) (ala A' / B' on rust) IMO if this feature is implemented should be optional. as introduces too much noise in the templates definitions

**Comment by andrewrk** [comment]
Closing in favor of #287
