### ISSUE TITLE
Tests failing on MacOS 

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#273]
LLD bug:  https://bugs.llvm.org/show_bug.cgi?id=32376

Here's the plan:

 * hope that LLD team fixes the bug in time for 0.1.0 release
 * ask mailing list for a workaround in the meantime (done)
 * ~if bug not fixed by 0.1.0 release, revert to using system linker on MacOS~

**Comment by andrewrk** [comment]
Some responses on the mailing list:

> CC'ing the owners as they may have ideas. Please consider that lld
MachO hasn't been touched in 6-9 months for anything real, at least.
Even if you work around this bug, chances are you'll find many others.
In other words, don't expect to be on par with ld64.

> Hello Andrew,
> 
> If you want to try to figure out what is up with the lazy binding info you might try running top of tree llvm-objdump with -lazy-bind to see what error it gives you (that is with my change from Monday with r298292).  The other thing you can do on a MacOS machine is:
> 
> xcrun dyldinfo -opcodes ./tmp_exe
> 
> to show the bind opcodes that the error message from llvm-objdump should be referring to. That may give you a start as to what is wrong if you want to try to fix the problem in lld.
> 
> My thoughts,
> Kev

I'll try this stuff out and see what happens, but it's looking like we may be stuck with depending on an external linker for MacOS.

I'm not sure why the LLVM project deprioritizes Mach-O so much, given that the team is funded by Apple.

**Comment by andrewrk** [comment]
We're not going to compromise cross compiling and depend on the system linker. The only options to fix this are:

 * Figure out if there are tweaks to the object files generated or in the LLD command line arguments to make it work
 * Submit a patch to LLD to fix the issue / implement the missing feature and wait for a new version of LLVM/LLD to be released, then depend on that version
 * Write our own linker for Mach-O as part of the zig codebase

**Comment by andrewrk** [comment]
http://lists.llvm.org/pipermail/llvm-dev/2017-July/115222.html

**Comment by aindigo** [comment]
Patch waiting for review : https://reviews.llvm.org/D35387  
if you apply this patch to lld you are going to be able to link with zig.

**Comment by andrewrk** [comment]
Worst case scenario, we fork lld and add it to the zig repo.

**Comment by andrewrk** [comment]
```
<andrewrk> so uh, what are the chances of https://reviews.llvm.org/D35387 making it into 5.0.0 at this point?
<LebedevRI> it first needs to get into the svn..
<LebedevRI> more on topic, that diff should probably add some tests, to prevent the issues from reappearing
```

**Comment by andrewrk** [comment]
update from the review thread:

> I've made a couple of notes, and it would be great to get a test-case for this too, but otherwise it's looking good. Thanks so much for working on this!

**Comment by aindigo** [comment]
Ill look into this tomorrow, Im answering his comments right now.Also I have to see how the test are made so I can commit one for this case in particular.

**Comment by andrewrk** [comment]
I just added [the LLD bug](https://bugs.llvm.org/show_bug.cgi?id=32376) to the [LLVM 5.0 Release Blockers Meta Bug](https://bugs.llvm.org/show_bug.cgi?id=33849). Maybe someone will merge the fix!

**Comment by andrewrk** [comment]
They didn't merge the fix for 5.0. We'll fork LLD with this fix in place for zig 0.1.0

**Comment by andrewrk** [comment]
Zig is building successfully in the macos branch which is based on LLVM 5.0.0 rc3 with a patched LLD. We even have Travis CI building it for MacOS.

behavior tests all pass except for these 2:
 * `test "switch statement"`
 * `test "switch handles all cases of number"`

The thing in common here and exclusive to the other switch tests is that this exercises the exhaustive listing of all prongs. Indeed if I replace one of the prongs with `else => unreachable` then the test passes.

If I can figure out what's going on here and make this work I think we'll have all tests passing for MacOS, complete with CI testing. Then I just need to embed LLD into zig's codebase and apply the relevant patch.

**Comment by andrewrk** [comment]
I got these tests working with this patch to LLD that I sent to llvm-dev: http://lists.llvm.org/pipermail/llvm-dev/2017-August/116904.html
