### ISSUE TITLE
proposal: ability to specify tag type of enums, and set the tag value

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#305]
Example:

```zig
const u4 = @intType(false, 4);
const VGAColor = enum(u4) {
    Black = 0,
    White = 3,
    Blue = 10,
};

const VGAEntry = packed struct {
    c: u8,
    fg: VGAColor,
    bg: VGAColor,
};
```

So here we set the tag type of `VGAColor` to `u4`. Then we set the tag values for Black, White, and Blue. This would also work even if an enum value had a payload:

```zig
const Foo = enum(u8) {
    One = 10,
    Two: bool = 13,
};
```

The tag type has to support equality and comparison operators, and there's no operator overloading. So it pretty much limits it to integers.

Delete the ability to explicit cast enum tags to any integer and replace it with the ability to only explicitly cast to the tag type. So if you want to cast an enum tag to an integer, you have to specify the tag type.

**Comment by AndreaOrru** [comment]
+1

**Comment by raulgrell** [comment]
I agree, it's a nice feature with intuitive syntax.

**Comment by skyfex** [comment]
I would love to see this implemented soon. It would make Zig great for programming microcontrollers.

**Comment by andrewrk** [comment]
You can now specify the tag type in enums, as described in this issue. You can also access the tag type with `@EnumTagType(EnumType)`. However these things are left to do before the issue is complete:

 * [ ] allow enums with specified integer sizes in packed structs
 * [ ] support setting the integer tag value of enum fields as described
 * [ ] Delete the ability to explicit cast enum tags to any integer and replace it with the ability to only explicitly cast to the tag type.
