### ISSUE TITLE
Proposal: possibility to inline a function on the call site

### ISSUE THREAD

**Issue by AndreaOrru** [zig-lang/zig#306]
OSdev code can rely on inlining for correctness (e.g. when manipulating the stack), so it should be enabled even when optimizations are off.

**Comment by AndreaOrru** [comment]
Proposal: possibility to inline a function on the call site.

Example:
```
fn aFunction(anArgument: u64) {
   ... some code ...
}

fn anotherFunction() {
    ...
    inline aFunction(10); 
    ...
}
```

**Comment by andrewrk** [comment]
Now the alwaysinliner pass always runs in debug mode.

However, I noticed that it does not notice and inline functions unless those functions are referenced from exported functions. In practice this will work fine, but if you're messing around and looking at the output of build_obj in debug mode with non-exported functions, you might see some functions that did not get inlined.

I asked about it on the LLVM mailing list: http://lists.llvm.org/pipermail/llvm-dev/2017-April/111975.html

So now this issue is just the proposal to have the ability to specify inline at the callsite of a function.

**Comment by thejoshwolfe** [comment]
`inline foo(a, b)` is how Jai does it, and that looks really good.

Here's an idea for implementing this feature without any grammar modification: `@inlineCall(foo, a, b)`. That doesn't look as good, but it still works.

My main issue with the Jai syntax is that it's not clear where parentheses are allowed:

```zig
var c = inline foo(a, b);
var c = (inline foo)(a, b); // does this work?
var f = inline foo; // is this some special comptime thing
var c = f(a, b); // that expands here?
```

The apparently simple answer that `(inline foo)(a, b)` should be a syntax error is a little bit tricky to implement. It's not impossible, but it makes the grammar just a little bit nastier.

Or we could allow `var f = inline foo;`, and have that be of some special comptime-only type. maybe this isn't so crazy, but it's certainly at least a little hard to understand.

The `@inlineCall` proposal doesn't have any of these syntax issues, and it's immediately apparent how it works.

**Comment by andrewrk** [comment]
What if `inline foo(a, b)` was part of the grammar? So after the `inline` keyword you can either have `for` , `while`, or a function call.

`var c = (inline foo)(a, b); // does this work?`

No, expected '(' after 'foo'.

`var f = inline foo; // is this some special comptime thing`

No, expected '(' after 'foo'.

**Comment by thejoshwolfe** [comment]
How about these:

```zig
inline object.method();
inline handler_functions[comptime command_id]();
inline List(u32)();
inline (List(u32))();
```

`inline for` and `inline while` are interesting, but they needn't be called "inline". [Wikipedia](https://en.wikipedia.org/wiki/Loop_optimization) calls it "completely unrolling" the loop, so "inline" might actually be the wrong name for it. I don't have a proposal for those.

**Comment by thejoshwolfe** [comment]
I think the syntax in this issue needs some polish.

```zig
inline math.mulOverflow(); // error: expected function type, found '(namespace)'
inline (math.mulOverflow)(); // works. (except for the parameters.)
```
