### ISSUE TITLE
zig build system: install step

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#332]
* [x] `b.installCLibrary` for dynamic libraries
 * [x] `b.installCLibrary` for static libraries
 * [x] `b.installFile`
 * [x] `b.getInstallStep()` instead of having to make it automatically, and the other install APIs automatically make the install step depend on them
 * [ ] `b.installLibrary`
 * [ ] `b.installExecutable`

**Comment by AndreaOrru** [comment]
What about automatic cleaning?

**Comment by andrewrk** [comment]
For cleaning see #328
