### ISSUE TITLE
add float math functions to standard library

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#374]
Functions:
 * `fma`
 * `nan`
 * `abs`
 * `exp`
 * `exp2`
 * `loge`
 * `log2`
 * `log10`
 * `sqrt`
 * `cbrt`
 * `hypot`
 * `pow`
 * `sin`
 * `cos`
 * `tan`
 * `asin`
 * `acos`
 * `atan`
 * `atan2`
 * `sinh`
 * `cosh`
 * `tanh`
 * `asinh`
 * `acosh`
 * `atanh`
 * `ceil`
 * `floor`
 * `trunc`
 * `round`
 * `scalbn`
 * `isfinite`
 * `isinf`
 * `isnan`
 * `isnormal`
 * `signbit`

Constants:
 * `e`
 * `pi`

There is also a concept of floating point exceptions which libc lets you query after you do a floating point operation. To be considered if we want to support something like that.

**Comment by tiehuis** [comment]
I'm slightly interested in this. I've had a bit of a look so far. The following are decent references for implementation (most share some common history):
 - https://golang.org/src/math/
 - https://git.musl-libc.org/cgit/musl/tree/src/math

One question I had was regarding the handling of the multiple float types. libc for example has separate calls for float, double and long doubles in most places. This seems over the top for the moment and the go math library appears to forgo any explicit f32 routines and just implements f64 functions. This suggests at least that the simplistic upcasting approach doesn't have any glaring problems.

**Comment by andrewrk** [comment]
My plan was to have zig automatically dispatch to the correct floating point function based on the type. You can see an  example with the floor function in std/math.zig.

**Comment by tiehuis** [comment]
Makes sense. I'll use that method when experimenting with this.

**Comment by thejoshwolfe** [comment]
am i correct in guessing that all of the listed functions are float-in and/or float-out? this would be in contrast to integer math functions like `gcd`, `isprime`, or `sign` (sometimes).

**Comment by andrewrk** [comment]
Yes I believe these are all float functions, and the result is the same type as the input.

Side note, I think that go ignores f32 and only has f64 because it lacks generics and this was a way around that.

**Comment by tiehuis** [comment]
Made a repository here for the moment: https://github.com/tiehuis/zig-fmath

**Comment by andrewrk** [comment]
Wow nice work @tiehuis. I'll have a look at these and try to get some nice test cases going.

**Comment by tiehuis** [comment]
One thing I was considering regarding test-cases was to just export the functions under their c equivalents and link against the [libc-test](http://nsz.repo.hu/git/?p=libc-test;a=tree;f=src/math;hb=HEAD) cases here.

That being said, the differences between how errors are flagged and the rest could make this not completely straightforward and it may be easier just to rewrite these under zig.

**Comment by andrewrk** [comment]
That's a good idea. Another idea is to port the test cases to zig test. Should be pretty straightforward. If the test files are big they can go in different file that doesn't get installed with the standard library.

**Comment by tiehuis** [comment]
An initial implementation is currently complete. There are various edge cases that are currently unimplemented and still needs some improvement and tests, but the initial conversion to zig is complete at least.

See https://github.com/tiehuis/zig-fmath/issues/7 for some discussion questions about some improvements.

**Comment by andrewrk** [comment]
This is an incredibly huge contribution to zig @tiehuis. :tada: 

Would you like to become a member of the zig-lang organization and have commit access?

**Comment by tiehuis** [comment]
Sure! That would be much appreciated.

I'll merge these changes into a branch shortly once I've finalized some minor details. I would like to extend the test suite slightly before merging in to zig proper, but may as well tie into the existing test suite in another branch in one go.

**Comment by andrewrk** [comment]
I believe you should have write access to all the zig-lang repos now.

I went ahead and merged my partial port of errol3 floating point printing, since it didn't break the tests. It includes an implementation of `@bitCast`. Feel free to delete the partial code I ported from zig-fmath when you want to do the full merge.

**Comment by andrewrk** [comment]
Scheduling for 0.1.0 because @tiehuis has this all very close to completion.
