### ISSUE TITLE
Array syntax parsing compiler error

### ISSUE THREAD

**Issue by tiehuis** [zig-lang/zig#376]
The following program causes a segfault during build.

```
pub fn main() -> %void {
    var b: u8[40] = undefined;
}
```

Run with the following command:
```
zig build_exe test.zig
```

Current master branch compiler with release mode.
`565ac3e27acedcd8dd2e39eff07de571bbcc3a1b`

---

I presume I haven't missed anything and this syntax is invalid in all cases. If so, it would be good to have a good parse error for this since it is quite an easy mistake to make especially if one is more familiar with c array declarations.

**Comment by andrewrk** [comment]
Thanks for the report. Fixed
