### ISSUE TITLE
C import fails when including xmmintrin.h

### ISSUE THREAD

**Issue by scurest** [zig-lang/zig#389]
If I try to include `<xmmintrin.h>` (actually, if I try to include SDL, which includes it) I get "definition of builtin function" errors during building.

If I copy the contents of my `/usr/lib/clang/4.0.0/include/` folder into `zig/build/lib/zig/include`, the build will succeed. So possibly some kind of compatibility issue between clang and the files in `zig/c_headers`?

------

    $ cat src/main.zig 
    const xmm = @cImport(@cInclude("xmmintrin.h"));

    pub fn main() -> %void {
        _ = xmm; // Use xmm
    }

------

    $ cat build.zig 
    const Builder = @import("std").build.Builder;

    pub fn build(b: &Builder) {
        const mode = b.standardReleaseOptions();
        var exe = b.addExecutable("iss", "src/main.zig");
        exe.setBuildMode(mode);
        b.default_step.dependOn(&exe.step);
        b.installArtifact(exe);
    }

-------

    $ ~/zig/build/zig build --verbose
    /home/scurest/zig/build/zig build_exe /home/scurest/xmm/src/main.zig --cache-dir /home/scurest/xmm/zig-cache --output /home/scurest/xmm/zig-cache/iss --name iss
    /home/scurest/xmm/src/main.zig:1:13: error: C import failed
    const xmm = @cImport(@cInclude("xmmintrin.h"));
                ^
    /home/scurest/zig/build/lib/zig/include/xmmintrin.h:698:1: note: definition of builtin function '_mm_sfence'
    _mm_sfence(void)
    ^
    /home/scurest/zig/build/lib/zig/include/xmmintrin.h:783:1: note: definition of builtin function '_mm_getcsr'
    _mm_getcsr(void)
    ^
    /home/scurest/zig/build/lib/zig/include/xmmintrin.h:789:1: note: definition of builtin function '_mm_setcsr'
    _mm_setcsr(unsigned int __i)
    ^
    /home/scurest/zig/build/lib/zig/include/emmintrin.h:1266:1: note: definition of builtin function '_mm_clflush'
    _mm_clflush(void const *__p)
    ^
    /home/scurest/zig/build/lib/zig/include/emmintrin.h:1272:1: note: definition of builtin function '_mm_lfence'
    _mm_lfence(void)
    ^
    /home/scurest/zig/build/lib/zig/include/emmintrin.h:1278:1: note: definition of builtin function '_mm_mfence'
    _mm_mfence(void)
    ^
    /home/scurest/zig/build/lib/zig/include/emmintrin.h:1469:1: note: definition of builtin function '_mm_pause'
    _mm_pause(void)
    ^
    Process /home/scurest/zig/build/zig exited with error code 1

    Build failed. Use the following command to reproduce the failure:
    ./zig-cache/build /home/scurest/zig/build/zig . ./zig-cache --verbose

-------

    $ cp /usr/lib/clang/4.0.0/include/* ~/zig/build/lib/zig/include/
    $ ~/zig/build/zig build
    $ echo $?
    0

-------

    $ clang --version
    clang version 4.0.0 (tags/RELEASE_400/final)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /usr/bin

    $ ldd --version
    ldd (GNU libc) 2.25
    Copyright (C) 2017 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    Written by Roland McGrath and Ulrich Drepper.

    $ cd ~/zig && git rev-parse HEAD
    199bbb6292896330ced71dec2e5c58a49af5907e

**Comment by andrewrk** [comment]
I'll copy the headers from clang 4.0.0 into zig source tomorrow.

**Comment by andrewrk** [comment]
I noticed that you're trying to use SDL, so I went ahead and created this test program:

```zig
const c = @cImport({
    @cInclude("SDL2/SDL.h");
    @cInclude("epoxy/gl.h");
});
const panic = @import("std").debug.panic;
const cstr = @import("std").cstr;

pub fn main() -> %void {
    if (c.SDL_Init(c.SDL_INIT_VIDEO) != 0) {
        panic("SDL init error: {}", cstr.toSliceConst(??c.SDL_GetError()))
    }
    defer c.SDL_Quit();

    c.SDL_GL_SetAttribute(c.SDL_GL_CONTEXT_PROFILE_MASK, c.SDL_GL_CONTEXT_PROFILE_ES);
    c.SDL_GL_SetAttribute(c.SDL_GL_CONTEXT_MAJOR_VERSION, 2);
    c.SDL_GL_SetAttribute(c.SDL_GL_CONTEXT_MINOR_VERSION, 0);

    const win = c.SDL_CreateWindow(c"Hello World!", 100, 100, 640, 480, c.SDL_WINDOW_OPENGL) ?? {
        panic("unable to create window: {}", cstr.toSliceConst(??c.SDL_GetError()))
    };
    defer c.SDL_DestroyWindow(win);

    _ = c.SDL_GL_CreateContext(win);

    while (true) {
        var event: c.SDL_Event = undefined;
        while (c.SDL_PollEvent(&event) != 0) {
            if (event.type == c.SDL_QUIT)
                return;
        }
        c.glClearColor(1, 0, 0, 1);
        c.glClear(c.GL_COLOR_BUFFER_BIT);
        c.SDL_GL_SwapWindow(win);
    }
}
```

One error I got was that `c.SDL_INIT_VIDEO` wasn't available, but I fixed that with c0f9012bed2e0646d15d454cffb971f4b7368edf.

Now this is the current state of compilation for me:

```
/home/andy/tmp/hello-sdl.zig:14:28: error: integer value 21 cannot be implicitly casted to type 'enum_anon_$31'
    c.SDL_GL_SetAttribute(c.SDL_GL_CONTEXT_PROFILE_MASK, c.SDL_GL_CONTEXT_PROFILE_ES);
                           ^
/home/andy/tmp/hello-sdl.zig:15:28: error: integer value 17 cannot be implicitly casted to type 'enum_anon_$31'
    c.SDL_GL_SetAttribute(c.SDL_GL_CONTEXT_MAJOR_VERSION, 2);
                           ^
/home/andy/tmp/hello-sdl.zig:16:28: error: integer value 18 cannot be implicitly casted to type 'enum_anon_$31'
    c.SDL_GL_SetAttribute(c.SDL_GL_CONTEXT_MINOR_VERSION, 0);
                           ^
/home/andy/tmp/hello-sdl.zig:26:21: error: no member named 'SDL_Event' in '(C import)'
        var event: c.SDL_Event = undefined;
                    ^
/home/andy/tmp/hello-sdl.zig:27:17: error: no member named 'SDL_PollEvent' in '(C import)'
        while (c.SDL_PollEvent(&event) != 0) {
                ^
```

 * I believe the ones with `enum_anon_$xx` is a regression. I'll look into that.
 * The error with `SDL_Event` and `SDL_PollEvent` is due to `SDL_Event` using a union, which is issue #144 .

**Comment by andrewrk** [comment]
I added " complete symbol import of SDL2/sdl.h" to the checklist here: https://github.com/zig-lang/zig/issues/88#issuecomment-175283067.

**Comment by scurest** [comment]
Awesome, thanks!

I can confirm that with some very hacked-together code for unions, enough of SDL works to bring up a window.
