### ISSUE TITLE
Trailing commas?

### ISSUE THREAD

**Issue by scurest** [zig-lang/zig#392]
Trailing commas are currently allowed and forbidden in kind of unintuitive places.

    struct { x: i32, } // trailing comma necessary
    enum { X, } // same for enum
    fn(i32,) -> i32 // this is illegal
    f(1,2,) // illegal here too
    Foo { .x = 1, .y = 2, } // either way is okay here!

My personal preference would be to allow optional trailing commas everywhere. (I had a shot at implementing that [here](https://github.com/scurest/zig/commit/02f439881fc0e39d8b720972a1bafd86355a0e29)).

If you don't want trailing comma though, I think they should be disallowed in container initializers. That would make the grammar consistent, because currently the `list(X, ",")` for `ContainerInitBody` allows them, but all the others don't.

----

Here's a list of all the cases where trailing commas can happen that I found

* Container initializer, eg. `Foo { .x = 1, }`: currently optional
* Container declarations: currently mandatory
* LHS of `=>` in switch, eg. `1,2, => ...`: currently forbidden
* After switch prongs, eg. `switch (x) { else => ..., }`: currently mandatory
* Assembly input/output/clobber lists: currently forbidden
* Actual parameter lists, eg. `f(1,)`: currently forbidden
* Formal parameter lists, eg. `fn(x: u32,)`: currently forbidden (if they're allowed, what about after varargs? `fn(...,)`?)

For container declaraitons and switch prongs, allowing a trailing comma complicates the grammar though, eg.

        ContainerMember = (ContainerField | FnDef | GlobalVarDecl)
        ContainerFieldNoComma = Symbol option(":" Expression)
        ContainerField = ContainerFieldNoComma ","
        ContainerDecl = option("extern" | "packed") ("struct" | "enum" | "union") "{" many(ContainerMember) option(ContainerFieldNoComma) "}"

**Comment by andrewrk** [comment]
> My personal preference would be to allow optional trailing commas everywhere.

I agree with this. I think the language becomes simpler if you can say "everywhere there is a comma separated list, a trailing comma is optional".

Thanks for starting the work with a patch. Maybe we can add a new file `test/cases/syntax.zig` (and add the corresponding code in `test/behavior.zig`) with these trailing/optional comma examples. If you created test cases for the above bulleted list, I'll take it from there. The actual body of the tests can essentially be a no-op - we're just testing that the syntax gets accepted by the compiler.

**Comment by scurest** [comment]
How's [this](https://github.com/scurest/zig/commit/457ae28fa596967cf5a6b88537326461cf91e61b) look?

**Comment by andrewrk** [comment]
Perfect! Let me see if I can get this to pass. Unless you wanted to go for it? I don't want to steal your thunder.

**Comment by scurest** [comment]
Ah, no you go for it; that sounds safer :) If it helps at all, that test case passes with the patch I gave above.

**Comment by andrewrk** [comment]
Cool, I merged your changes verbatim. Thanks for the contribution!
