### ISSUE TITLE
Alignment of enums

### ISSUE THREAD

**Issue by scurest** [zig-lang/zig#396]
The alignment of enums is currently wrong. For example

    const Foo = enum {
        Biggest: [9]u8,
        MostAligned: u64,
    };

has `@alignOf(Foo) == 1` (on x86_64).  This is because the LLVM type for the union in the enum is just taken to be the type of its largest member, which isn't necessarily aligned strictly enough. SO suggests using a struct containing

* the most aligned member
* (size of largest member - size of most aligned member) bytes of padding

I implemented this [here](https://github.com/scurest/zig/commit/57e52cd82af3733402ea05aa3bcc0ff547d0c8df).

There's something I don't understand though: why are the `debug_align` values are computed with `LLVMABISizeOfType`, instead of `LLVMABIAlignmentOfType`? Is that right?

Also, does codegen need to be changed at all if the representation of this union changes?

**Comment by andrewrk** [comment]
The LLVM exposed functions we have available are:

```c
/** Computes the size of a type in bytes for a target.
    See the method llvm::DataLayout::getTypeSizeInBits. */
unsigned long long LLVMSizeOfTypeInBits(LLVMTargetDataRef TD, LLVMTypeRef Ty);

/** Computes the storage size of a type in bytes for a target.
    See the method llvm::DataLayout::getTypeStoreSize. */
unsigned long long LLVMStoreSizeOfType(LLVMTargetDataRef TD, LLVMTypeRef Ty);

/** Computes the ABI size of a type in bytes for a target.
    See the method llvm::DataLayout::getTypeAllocSize. */
unsigned long long LLVMABISizeOfType(LLVMTargetDataRef TD, LLVMTypeRef Ty);

/** Computes the ABI alignment of a type in bytes for a target.
    See the method llvm::DataLayout::getTypeABISize. */
unsigned LLVMABIAlignmentOfType(LLVMTargetDataRef TD, LLVMTypeRef Ty);

/** Computes the call frame alignment of a type in bytes for a target.
    See the method llvm::DataLayout::getTypeABISize. */
unsigned LLVMCallFrameAlignmentOfType(LLVMTargetDataRef TD, LLVMTypeRef Ty);

/** Computes the preferred alignment of a type in bytes for a target.
    See the method llvm::DataLayout::getTypeABISize. */
unsigned LLVMPreferredAlignmentOfType(LLVMTargetDataRef TD, LLVMTypeRef Ty);

/** Computes the preferred alignment of a global variable in bytes for a target.
    See the method llvm::DataLayout::getPreferredAlignment. */
unsigned LLVMPreferredAlignmentOfGlobal(LLVMTargetDataRef TD,
                                        LLVMValueRef GlobalVar);

```

I suspect that we may need to remove `@alignOf` in favor of `@preferredAlignOf` and `@abiAlignOf`.

> There's something I don't understand though: why are the debug_align values are computed with LLVMABISizeOfType, instead of LLVMABIAlignmentOfType? Is that right?

I don't remember the logic that went into this. But I think we should use preferred alignment instead of ABI alignment, unless the type needs to be ABI compatible, such as a struct declared `export` or `extern`.

Thanks for your patch, I'll look at this in a little bit.

Can I ask, what is your particular use case for checking alignment? That will help me understand better how all this should work.

**Comment by andrewrk** [comment]
> Also, does codegen need to be changed at all if the representation of this union changes?

It may. The codegen depends on the struct having the tag integer in the first position, and the union in the second. Certainly tests would fail if the codegen for this broke.

**Comment by scurest** [comment]
> Certainly tests would fail if the codegen for this broke.

Oh, okay good! I didn't change the order of the tag and union (but that would usually be a good idea; it would bring the size of `Foo` down from 24 to 16.)

> Can I ask, what is your particular use case for checking alignment?

I'm only using `@alignOf` to check for correctness. I got off on this because I tried to implement unions and I was checking that the alignment was correct. Technically, for that purpose, since the preferred alignment is >= the ABI alignment, it doesn't matter which I get. I think the ABI alignment is what I expect though. I know that's what eg. `align_of` in Rust returns.

**Comment by andrewrk** [comment]
> Oh, okay good! I didn't change the order of the tag and union (but that would usually be a good idea; it would bring the size of Foo down from 24 to 16.)
> 

In zig the layout of enums in memory is not defined, so we can actually compare preferred alignment for both fields and put the best choice first for any given enum.

> I got off on this because I tried to implement unions and I was checking that the alignment was correct.

Aha! So I do want to make this alignment behavior better. But I could actually solve your use case better by getting a move on with supporting raw unions.

**Comment by scurest** [comment]
Haha, yes :) If enums can reuse the code for raw unions for their union member, alignment becomes raw union's problem anyway.

**Comment by andrewrk** [comment]
Thanks again for your patch. Sorry it took so long to merge.

I went ahead and implemented the thing where codegen chooses the best way to order tag and union fields based on which preferred alignment is bigger.

I hope you'll come back and play around some more when we release 0.1.0! Only 6 more issues left in the milestone.
