### ISSUE TITLE
Find LLVM based on LLVMConfig.cmake

### ISSUE THREAD

**Issue by philix** [zig-lang/zig#400]
You can add a simple snippet to CMakeLists.txt [1] and build like this:

    $ LLVM_DIR=~/src/llvm/build cmake -G Ninja .. # Custom LLVM tree
    $ cmake -G Ninja ..        # LLVM installed on the system

[1] http://llvm.org/docs/CMake.html#embedding-llvm-in-your-project

**Comment by andrewrk** [comment]
Neat. I expect users who want this to do it ad hoc. The most useful way for the build system to work by default right now is assuming a system LLVM package

**Comment by philix** [comment]
CMake will look for the system LLVM if you don't define LLVM_DIR.

**Comment by andrewrk** [comment]
I would accept a pull request, but not planning on implementing this myself.
