### ISSUE TITLE
Unable to evaluate type defined in function body

### ISSUE THREAD

**Issue by scurest** [zig-lang/zig#402]
fn foo() {
        const S = struct {};
        const T = struct { x: S };
    }

gives

    error: unable to evaluate constant expression
        const T = struct { x: S };
                              ^

**Comment by andrewrk** [comment]
This works now. The bad news is, structs declared inside functions get named after the function they're in (consider e.g. `ArrayList(u32)`). I opened a new issue for this: #675

**Comment by andrewrk** [comment]
see also #672
