### ISSUE TITLE
Debug safety: shifting by >= bit width

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#403]
In C, x << y or x >> y where y is >= bit width of x is undefined behavior. It should also be the case in zig, with appropriate debug safety.

**Comment by andrewrk** [comment]
It might make sense to allow shifting right by a number == bit width. This would be equivalent to assigning to zero.

**Comment by andrewrk** [comment]
The decision is to have the type of the right hand side be an integer with a log2 bit count of the left hand side.

So if shifting a `u32`, the type of right hand side is `u5`.

There's an issue when the left hand side is a non-power-of-2 integer type, such as `u31`. I suppose for these situations we can insert a debug safety check. It should be very rare in practice.

**Comment by andrewrk** [comment]
Due to this issue, I'm adding these primitive types:
 * `u3` (for shifting `u8`) (and `i3` for consistency)
 * `u4` (for shifting `u16`) (and `i4` for consistency)
 * `u5` (for shifting `u32`) (and `i5` for consistency)
 * `u6` (for shifting `u64`) (and `i6` for consistency)
 * `u7` (for shifting `u128`) (and `i7` for consistency)

**Comment by tiehuis** [comment]
Having to shift with by a number == bit width has come up a fair few times in code I've been writing.

For example the following will get a compile error.

```
const T = @typeOf(a);
const b = a << Log2Int(a)(T.bit_count - offset)
```

The current workaround is simply to separate the cases for possibly larger shifts.

```
const T = @typeOf(a);
const b = if (offset == 0) {
    0
} else {
    a << Log2Int(a)(T.bit_count - offset)
}
```

This is a little ugly, and unfortunately we can't really seem to get around this without changing the types allowed as shift arguments (which is a nice solution in general for all other values).

I don't think the default should be changed, but a possible alternative could be to add an extra `shiftLeftWide` which takes a `T` as a shift value instead. Anyway, a minor right now. This is mainly a note that this case comes up in practice ocassionally.

**Comment by andrewrk** [comment]
That's interesting. I think this is evidence that this safety is really important, because that ugly if statement is what you have to do to avoid undefined behavior. If we added a builtin function `@shlWide` it would just contain exactly the logic above, since the LLVM shift operation has undefined behavior for shifting >= number of bits of the integer. 

Maybe this can simply be in the standard library?

`@import("std").math.shl`

we currently have:

```
error Overflow;
pub fn shl(comptime T: type, a: T, shift_amt: Log2Int(T)) -> %T {
    var answer: T = undefined;
    if (@shlWithOverflow(T, a, shift_amt, &answer)) error.Overflow else answer
}
```

we could introduce:

```
/// Shifts left. Overflowed bits are truncated.
/// A signed shift amount results in a right shift by that many bits.
pub fn shlTrunc(comptime T: type, a: T, shift_amt: var) -> T {
    const abs_shift_amt = absCast(shift_amt);
    const casted_shift_amt = if (abs_shift_amt >= T.bit_count) return 0 else Log2Int(abs_shift_amt);

    if (T.is_signed) {
        if (shift_amt >= 0) {
            return a << casted_shift_amt;
        } else {
            return a >> casted_shift_amt;
        }
    }

    return a << casted_shift_amt;
}
```

**Comment by andrewrk** [comment]
Actually now that `<<` is truncating left shift, we should make what is above `math.shlTrunc` named `math.shl`, and `math.shl` rename to `math.shlExact`

**Comment by tiehuis** [comment]
That sounds good. `shl` not returning an error makes a bit more sense API-wise as well.

**Comment by frmdstryr** [comment]
I know this is an old issue but having just killed several hours because of a shift overflow. I thought these types of errors  would be caught in debug/safe mode like an add overflow... but was wrong.

Would it make sense to have the `<<` operator be changed to do a `@shlExact` and a new operator `<<%` be added to do `@shlWithOverflow` to be consistent with the other operators?

**Comment by lobre** [comment]
I also know this is an old issue, but I wonder why the right-hand side type is chosen to be an integer with a log2 bit count of the left-hand side? I can’t find many details apart from this issue.

Is it simply because the maximum allowed shift before reaching the undefined behavior is contained in the type representing this log2 of the left-hand side? So allowing a "bigger" type would not make sense?

**Comment by nektro** [comment]
yep
