### ISSUE TITLE
syntax for creating a symbol alias

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#420]
http://llvm.org/docs/LangRef.html#aliases

> Aliases, unlike function or variables, don’t create any new data. They are just a new symbol and metadata for an existing position.

**Comment by andrewrk** [comment]
Maybe we don't do this since you can pretty easily accomplish it with module level assembly (#256)

**Comment by raulgrell** [comment]
I'm not sure if this is what you mean, but I'd really like a way to be able to refer to the elements of an array in a struct by another name (like with an anonymous union), where something like this would be valid:

```
const Vec2 = struct {
       data: [2]f32,
      alias x = this.data[0];
      alias y = this.data[1];
}

var vec = Vec2 { .data = []f32 { 0, 0} };
vec.x = 1;
vec.y = vec.x * 2;
```

**Comment by andrewrk** [comment]
Now that we have packed structs you can do this:

```zig
const Vec2 = packed struct {
    x: f32,
    y: f32,
};
```
and memory layout is guaranteed to be exactly as you describe. That would solve your use case I believe.

As for this issue, it's referring to the ability for ELF files to have multiple symbols that point to the same address in virtual address space.
