### ISSUE TITLE
compiler test errors

### ISSUE THREAD

**Issue by tiehuis** [zig-lang/zig#428]
Currently testing the release compiler fails following the behavior tests for me.

I've narrowed it down with a bisect to this commit. https://github.com/zig-lang/zig/commit/09bd4a9a8693485fa87a5f62af90540ca8ce9d47

#### Output

```
./zig 
...
Test 272/272 behavior-ReleaseFast-c while on bool with else result follow break prong...OK
unreachable
Process ./zig terminated unexpectedly

Build failed. Use the following command to reproduce the failure:
./../zig-cache/build ./zig ./.. ./../zig-cache test
```

#### Build Details

```
$ g++ --version
g++ (GCC) 7.1.1 20170630
$ clang++ --version
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$(pwd) \
    -DZIG_LIBC_LIB_DIR=$(dirname $(cc -print-file-name=crt1.o)) \
    -DZIG_LIBC_INCLUDE_DIR=$(echo -n | cc -E -x c - -v 2>&1 | grep -B1 "End of search list." | head -n1 | cut -c 2- | sed "s/ .*//") \
    -DZIG_LIBC_STATIC_LIB_DIR=$(dirname $(cc -print-file-name=crtbegin.o))
```

### Investigation

Interestingly, `clang++` runs the behavior tests fine but fails following the compiler-rt math tests. Unless the test ordering differs otherwise, not sure yet.

Tracing `zig_unreachable` gives the following error location for both compilers:

```
3438:gen_const_val() /home/me/src/zig/src/codegen.cpp
```

There was one call to this function added to that commit here:

https://github.com/zig-lang/zig/blob/0a922d3bca7fc65a9280f4869afce73a55b9c9cf/src/codegen.cpp#L3953-L3956

Looks as if `coerced_value` has an uninitialized `special` field being set to zero by the compiler which is the `ConstValSpecialRuntime` enum member, causing the `zig_unreachable()` function to be called.

Might just be getting lucky on the CI and other compilers.

**Comment by tiehuis** [comment]
Just to add; adding the following line makes all tests pass for me, not too knowledgeable on the codegen here though.

```
             coerced_value.special = ConstValSpecialStatic;
```

**Comment by andrewrk** [comment]
Thanks for this, your proposed solution is correct.
