### ISSUE TITLE
Allow compile time array concatenation to accept void

### ISSUE THREAD

**Issue by krisnye** [zig-lang/zig#435]
If you make it so an Array concatenated with a void just returns the Array then some of your use cases become much simpler. This also assumes that your compiler will type an if expression without an else as Type | void.

```
const available_backends =
    if (@compileVar("have_jack"))
        []SoundIoBackend{SoundIoBackend.Jack}
    ++
    if (@compileVar("have_pulse_audio"))
        []SoundIoBackend{SoundIoBackend.PulseAudio}
    ++
    if (@compileVar("have_alsa"))
        []SoundIoBackend{SoundIoBackend.Alsa}
    ++
    if (@compileVar("have_core_audio"))
        []SoundIoBackend{SoundIoBackend.CoreAudio}
    ++
    if (@compileVar("have_wasapi"))
        []SoundIoBackend{SoundIoBackend.Wasapi}
    ++
    []SoundIoBackend{SoundIoBackend.Dummy};

```

**Comment by andrewrk** [comment]
Is this simpler?

Without knowing the proposed rule that `void` and `[N]T` can implicitly combine into `[N]T`, this example takes more knowledge to comprehend.

Some selected bullet points from the [Zen of Zig](http://ziglang.org/documentation/#zen):

 * Communicate intent precisely.
 * Favor reading code over writing code.
 * Only one obvious way to do things.

**Comment by krisnye** [comment]
That rule is pretty simple though. void concatenated with any other type is just that other type.

If you don't allow that then I would say that the rules are equally complicated in another way.

You are using this as an expression:

```
if (x)
    b
else
    c
```
I assume this is also an expression:
```
if (x)
    b
else if (y)
    c
else
    d
```
Why then is this not an expression:
```
if (x)
    b
````

Using conditional statements as expressions is a good idea. It enables a clean and concise declarative specification of structures.

I may be a bit biased since I wrote a language that embraces a declarative specification of nested structures. Here is some example code (not the exact syntax):

```
let array = [
    10
    20
    30
    if (foo)
        40
    50
]
```

I'm pretty sure that even someone who's never seen code like this would understand what's going on.

`if (x) value`  clearly implies that if not x then don't add the value.

**Comment by andrewrk** [comment]
```zig
if (x)
    b
```

This is indeed an expression, and if `x` is compile-time known, then the result type of the expression is either `@typeOf(b)` (`x == true`) or `void` (`x == false`).

So this proposal is only proposing that a `[N]T` `++` a `void` results in the `[N]T`.

I'll consider it. I'd like to get @thejoshwolfe's opinion.

**Comment by krisnye** [comment]
Cool. Can you explain the terminology you use to describe this type format: `typeOf(b) (x == true)`

Specifically the right side `(x == true)` 

What do you call that part and is there some type theory underlying it?

**Comment by andrewrk** [comment]
I was just using shorthand. Here's another example:

```zig
const x = true;
const result = if (x) b;
assert(@typeOf(result) == @typeOf(b));
```

```zig
const x = false;
const result = if (x) b;
assert(@typeOf(result) == void);
```
