### ISSUE TITLE
Buffer.endsWith doesn't take actual buffer length into account

### ISSUE THREAD

**Issue by jean-dao** [zig-lang/zig#443]
In `Buffer.endsWith`:
```
pub fn endsWith(self: &const Buffer, m: []const u8) -> bool {
        const l = self.len();
        if (l < m.len) return false;
        const start = l - m.len;
        return mem.eql(u8, self.list.items[start..], m);
}
```

In the last line we compare `self.list.items[start..]` which actually refers to the whole allocated slice, with contains the final null byte and maybe some more allocated but not used memory after it (allocated in `ArrayList.ensureCapacity`).

We should only compare the actual string, excluding the null byte with `self.list.items[start..l]`. The `m` string slice should be null terminated.

**Comment by andrewrk** [comment]
Thanks!
