### ISSUE TITLE
Find solution for u128 in the compiler

### ISSUE THREAD

**Issue by marler8997** [zig-lang/zig#477]
We can use this "issue" to track any investigations into libraries to support 128-bit precision arithmetic.

The GNU GMP library looks like a good candidate but it is licensed through the GPL which makes it incompatible with the Zig compiler since it uses the MIT license.

**Comment by marler8997** [comment]
Another idea is to wait for the zig implementation (issue #364) and then port it to c++.  Note that once zig self hosts then the standard library implementation will be what the compiler uses.

**Comment by marler8997** [comment]
nevermind, removed 128 bit integers from compiler :)

**Comment by andrewrk** [comment]
#302 depends on this
