### ISSUE TITLE
Maintain a document that describes rejected/in progress proposals

### ISSUE THREAD

**Issue by marler8997** [zig-lang/zig#481]
As Zig gets more popular there will be alot of improvement proposals and potentially rediscussion of the same points.  It is proposed that "rejected" or "in progress" proposals be put into a single central document that can easily be linked to when discussing these topics and serve as a reference for developers to recall the pros and cons of particular ideas.

Unlike a discussion thread, this contents of this document will be approved/maintained by the language maintainers and contain the points that can be found in a discussion thread but in a summarized format.  This document and the sections within it should be easily linked to for the purposes of referencing them in further discussion.

**Comment by tiehuis** [comment]
I think this is a good idea.

I've started a wiki page for the moment with some preliminary links after going through the issues. I'd like to group together related issues and write better summaries in order to make the page more easily searchable.

We can switch from a wiki page if the need arises as you suggest.

https://github.com/zig-lang/zig/wiki/Zig-Proposals

**Comment by andrewrk** [comment]
How about adding the following labels:

 * proposal
 * rejected
 * accepted

Then you can use normal issue search. Does this solve the problem?

**Comment by tiehuis** [comment]
This is useful and certainly helps. I think a document though which groups and summarizes the outcome of why something may have been rejected or what changes may have been made to something which was accepted would still help the discoverability.

I'll add the following labels sometime today and see how it fares first though.

**Comment by tiehuis** [comment]
I've updated the document to just provide links with appropriate filters to the existing issues. I think that we do not have enough proposals as is to give enough worth to more in-depth summaries. Keeping one source of truth is easier to maintain right now as well.

Can revisit summaries and the like in the future.
