### ISSUE TITLE
proposal: define behavior for arithmetic and shift operators to eliminate UB

### ISSUE THREAD

**Issue by kyle-github** [zig-lang/zig#512]
This comes to light from #509, #422 and #403.

This would be a breaking change.

Some languages, Java for instance, specify a very specific arithmetic model.   This model maps well to most common processors but can incur overhead.   

What I am proposing here is that the standard arithmetic operators, `+ - * / << >>` etc., all have a completely specified set of behavior.  No UB.   For performance reasons, alternate forms of the operators could be used by coders that know what will happen on their specific combination of OS and hardware. 

Examples:

Operator | Behavior | UB-unsafe Alternate
----------|-----------|----------
`+`| Signed arithmetic: automatic overflow as for 2's complement arithmetic.   Unsigned: automatic wrapping around zero.   Mixed arithmetic: not allowed. | `+.` uses `add` instruction or nearest equivalent on the target CPU.
`-` | Signed arithmetic: automatic underflow as for 2's complement arithmetic.  Unsigned: automatic wrapping around zero.   Mixed: not allowed. | `-.` use `sub` instruction or nearest equivalent.
cast| Cast from unsigned to signed: The bit pattern is interpreted as if it were in 2's complement format.  Note that casting between different sized integers is disallowed. | ?
`<<`| signed: shifts bit patterns in the integer assuming 2's complement encoding with truncation of bits that fall off the top. Unsigned: ... | `<<.` uses whatever the closest instruction is in the target CPU.

This is far from complete.   

The purpose of this is to make Zig have no surprises.   If I see `a<<b` I know what is going to happen on every platform.  If I see `a <<. b`, I know to look up the target platform and see what is going to happen.

The performance cost on most platforms will be near zero but it would eliminate a large source of UB in arithmetic expressions.   Allowing the coder to chose the "fast-but-maybe-not-accurate" version allows performance sensitive areas to be tuned after programs are determined to be correct.

**Comment by andrewrk** [comment]
We have already eliminated undefined behavior for shifting.

If you want defined overflow for integer math, use the modulo operators: http://ziglang.org/documentation/#undef-int-overflow-wrap

See also [@bitCast](http://ziglang.org/documentation/#builtin-bitCast)

**Comment by kyle-github** [comment]
D'oh! Missed that part in the docs.   However, this makes it easy to use UB and hard to use non-UB.   So, I think the core of the proposal stands: make the non-UB versions the default and the UB-unsafe versions the special versions.

There is also a difference between these.   In my proposal, I am arguing to allow things like wrapping.  However, it should be specified.     The `+%` cause a runtime error.

Thanks for considering this.

**Comment by andrewrk** [comment]
It's better to use the undefined behavior operators by default, because the safety catches bugs, and you get faster code in release-fast mode.

> Communicate intent precisely.

Similarly you should use [@divExact](http://ziglang.org/documentation/#builtin-divExact) if you know that your division operation should not have a remainder, even though it introduces undefined behavior (in release-fast mode) if there actually is a remainder.

**Comment by kyle-github** [comment]
Safety only catches bugs when you trigger the right inputs.   Having a well defined set of operators as the default gives safety at all times.   I guess I would argue that I come at this from the same set of goals but arrive in a different place.

Thanks for reading.

**Comment by andrewrk** [comment]
If your integer overflows and wraps around, and you didn't expect it to, you have undefined behavior in the form of a logic bug. The wraparound actually hurts here because it introduces a logic bug that tools like valgrind or ubsan can't help with.
