### ISSUE TITLE
Question about usability of generic structure definition

### ISSUE THREAD

**Issue by PavelVozenilek** [zig-lang/zig#521]
This is stdlib's HashMap:

```
pub fn HashMap(comptime K: type, comptime V: type,
    comptime hash: fn(key: K)->u32,
    comptime eql: fn(a: K, b: K)->bool) -> type
{ ... }

```

It is constructed like this:

`var map = HashMap(i32, i32, hash_i32, eql_i32).init(&debug.global_allocator);
`

Am I supposed to write function with hash map parameters this way:

```
fn foo(map1 : &HashMap(i32, i32, hash_i32, eql_i32), map2 : &HashMap(i32, i32, hash_i32, eql_i32), map3 : &HashMap(i32, i32, hash_i32, eql_i32)) 
{ 
... 
}

```
This would be usability nightmare. Some types passed into the constructor may not be visible where HashMap is used.

Is there some way to define short alias for complex generics?

**Comment by thejoshwolfe** [comment]
```zig
const I32Map = HashMap(i32, i32, hash_i32, eql_i32);

fn foo(map1 : &I32Map, map2 : &I32Map, map3 : &I32Map) 
{ 
... 
}
```

**Comment by PavelVozenilek** [comment]
@thejoshwolfe: thanks!
