### ISSUE TITLE
allow multiple kinds of return types from main

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#535]
Currently, this is the main entry point function:

```zig
pub fn main() -> %void {

}
```

The bootstrap code runs it, checks the return value, and makes the exit/ExitProcess syscall.

If a zig user wants to do their own process exiting, however, they should be able to make the return type `noreturn`, and then the bootstrap code does not need to handle cleanup.

This shaves off a couple of bytes of bloat for some of our more hardcore users such as demoscene programmers.

**Comment by thejoshwolfe** [comment]
Another usecase for returning `noreturn` is if a program can't stop, won't stop. This is common for daemons such as [groovebasin](https://github.com/andrewrk/groovebasin).

**Comment by skyfex** [comment]
Microcontroller firmware is one more usecase.

**Comment by andrewrk** [comment]
more proposal:

allow multiple kinds of return types from main

* `noreturn` - main never returns
* `void` - main does not fail
* `%void` - possibly print an error return trace


```zig
switch (@typeId(@returnType(root.main))) {
    builtin.TypeId.NoReturn => {
        root.main();
    },
    builtin.TypeId.Void => {
        root.main();
        std.os.exit(0);
    },
    builtin.TypeId.ErrorUnion => {
        if (builtin.mode == builtin.Mode.ReleaseFast) {
            root.main() catch std.os.exit(1);
            std.os.exit(0);
        } else {
            root.main() catch |err, trace| {
                std.debug.warn("error: {}\n", @errorName(err));
                std.debug.dumpStackTrace(trace);
                std.os.exit(1);
            };
            std.os.exit(0);
        }
    },
    else => @compileError("expected return type of main to be 'noreturn', 'void', or '%void'"),
}
```
