### ISSUE TITLE
Bad ELF generation on freebsd

### ISSUE THREAD

**Issue by tiehuis** [zig-lang/zig#553]
Using the freebsd branch I'm working on: https://github.com/zig-lang/zig/tree/freebsd

Have got executables compiling without errors but the generated ELF's appear to use the UNIX System V ABI (type 0).

```
$ (freebsd) zig build-exe t.zig 
$ (freebsd) ./t
ELF binary type "0" not known.
```

Just to check, I tried rebranding as a GNU elf and using the linux compatibility layer built in to FreeBSD but segfaults, which makes sense. There is a specific FreeBSD OS ABI of type 9, but not really that familiar with how oses want their elf files.

Will have a closer look at some point.

**Comment by andrewrk** [comment]
One clue is to have a look at what clang does. We can look at the difference in the LLVM IR generated by clang and by zig. And see if clang generates ELF files that are correct or the same as Zig.

**Comment by krytarowski** [comment]
FreeBSD is almost the only OS out there to set this value. Other systems like NetBSD set this to System V ABI.
