### ISSUE TITLE
Proposal: Create RFC project under zig-lang

### ISSUE THREAD

**Issue by steveno** [zig-lang/zig#559]
If you do a search, there are a lot of proposals here. That's great for zig! It's also clogging up the issues list for zig itself. This should be an area for bug reports.

Rust has the https://github.com/rust-lang/rfcs repository. It's very official, and formal, and I'm not suggesting it has to be that polished, but I think it would help zig to have something similar.

**Comment by andrewrk** [comment]
I personally find it convenient to have everything in one place. Are GitHub's label searching features insufficient? Did you try to search for something and couldn't find it?

**Comment by steveno** [comment]
No. I haven't had any issues, it's more a personal preference I suppose. 

I will add that I think the difference between an "Enhancement" and a "Proposal" is arguably nonexistent. You could argue that every proposal is an enhancement, otherwise it wouldn't be proposed.

**Comment by Perelandric** [comment]
I would assume `proposal` issues have not yet been accepted, while `enhancement` issues have. If any of the `enhancement` issues have not been accepted, then it seems like they should get the `proposal` tag too.

**Comment by andrewrk** [comment]
behavior changes are either enhancements or bugs. 

if it's doing something against how it's documented to work, or at least how it would be documented to work if it were documented, then it's a bug. otherwise it's an enhancement. 

proposals are proposing to change how something is documented to work.

**Comment by hasenj** [comment]
Sounds like a maintenance headache. You'd have to specify a format and spend a lot of time writing things up and make it very formal, etc.

Suitable for organizations with many maintainers, maybe. I don't think it makes sense for Zig.
