### ISSUE TITLE
Add ability to emit asm directly

### ISSUE THREAD

**Issue by tiehuis** [zig-lang/zig#571]
An `--emit` argument which allows this would be nice to more easily verify the assembly generated by zig/llvm would useful for integrating with other tools.

We currently can view ir to stdout via the `verbose-llvm-ir` for example, but the only way to get assembly is to use objdump on the resulting binary.

The use case I have for this is to better integrate https://github.com/mattgodbolt/compiler-explorer, for which I have a local fork working with zig.

**Comment by andrewrk** [comment]
Very cool. It would be exciting to get zig as one of the compiler options in official godbolt.

How about:

 * `--emit bin` (default)
 * `--emit llvm-ir` 
 * `--emit asm`

For assembly, we can add this without too much effort. Here's the relevant code:

https://github.com/zig-lang/zig/blob/f1072d0d9fba397b3920015fd854414868e6ea17/src/zig_llvm.cpp#L147

We can add a parameter to `ZigLLVMTargetMachineEmitToFile` to change that 

...oh, wait a minute, we already have that `file_type` parameter. All we have to do is pass the correct `LLVMCodeGenFileType` to `ZigLLVMTargetMachineEmitToFile`.

**Comment by tiehuis** [comment]
Made an initial start on this. It emits all the formats now and seems to work okay. Could clean up the passing of file types to the llvm emit function and need to determine an llvm error I get emitting assembly files but otherwise is mostly complete.

https://github.com/zig-lang/zig/commit/87adb0f9855174152d529af497ee6888a3726151
