### ISSUE TITLE
Compiling with lld<5?

### ISSUE THREAD

**Issue by omrisim210** [zig-lang/zig#573]
I'm trying to make a package for Void Linux, which only has lld 4. Even after specifying `DZIG_FORCE_EXTERNAL_LLD=ON` it used the embedded lld and I get an error (the error can be found [here](https://forum.voidlinux.eu/t/xbps-src-passing-d-arguments-to-cmake/3725/4)) when trying to build Zig.  
Does it use lld 5+ specific functions, and is there a way to build it on systems with lld<5?

**Comment by andrewrk** [comment]
The only supported LLD in Zig right now is the LLD embedded in this git repository. It has some patches on top of official LLD 5.

**Comment by omrisim210** [comment]
Void only has llvm and clang 4. Does that mean I can't build Zig until Void gets llvm and clang 5?

**Comment by andrewrk** [comment]
You can also build llvm and clang from source: https://github.com/zig-lang/zig/wiki/How-to-build-LLVM%2C-libclang%2C-and-liblld-from-source#posix

**Comment by andrewrk** [comment]
oh, and we also have a docker image: https://github.com/zig-lang/docker-zig
