### ISSUE TITLE
Tab character not considered whitespace.

### ISSUE THREAD

**Issue by Jezza** [zig-lang/zig#584]
The top one works, but the bottom one errors out with: `error: invalid character: '\t'`

```
pub fn main() -> %void {
    @import("std").debug.warn("Hello, world!\n");
}
```
vs
```
pub fn main() -> %void {
	@import("std").debug.warn("Hello, world!\n");
}
```

**Comment by scurest** [comment]
cf. #544

Maybe we could add this to `invalid_char_error`

```
    } else if (c == '\t') {
        tokenize_error(t, "invalid horizontal tab, use spaces instead"); 
```

**Comment by Jezza** [comment]
I'm curious as to the design choice behind rejecting tabs as indentation...

**Comment by andrewrk** [comment]
Arguing about tabs vs spaces is for other languages. In Zig nobody argues about tabs vs spaces. Instead we work on writing robust, high performing software.

**Comment by Jezza** [comment]
I don't want to start a flame war.
I was actually just wondering.

Because of that I'll probably have to put zig down.
