### ISSUE TITLE
std.heap: cAlloc, cRealloc redeclares mem

### ISSUE THREAD

**Issue by scurest** [zig-lang/zig#585]
```
const heap = @import("std").heap;
pub fn main() -> %void {
    _ = heap.c_allocator.alloc(u8, 100);
}
```

gives `error: redeclaration of variable 'mem'` at

https://github.com/zig-lang/zig/blob/4cc9fe90a8a3c0bce803bf9fffd66477da9e37d0/std/heap.zig#L20

`mem` just needs to be renamed. Same for `cRealloc`.

-------

I tried to do this but when I add a test that uses `c_allocator` to `heap.zig`, I get a mysterious linker error when I run the tests

```
lld: error: duplicate symbol: _start
>>> defined at init.c
>>>            /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib/Scrt1.o:(_start)
>>> defined at bootstrap.zig:16 (/home/scurest/zig/build/lib/zig/std/special/bootstrap.zig:16)
>>>            ./zig-cache/test.o:(.text+0x6FC00)
```

**Comment by tiehuis** [comment]
When using the c allocator you will need to use the `--library c` command line flag to link the c library.

**Comment by scurest** [comment]
Ah, that does makes sense :)

I see that in `addPkgTests` in `tests/tests.zig`, that it adds the tests once with and once without linking libc. So is the right thing to do to guard the test that needs it with `if (builtin.link_libc)`?

**Comment by andrewrk** [comment]
> So is the right thing to do to just guard the test that needs it with if (builtin.link_libc)?

Yes, this is right. Thanks for adding a test for this.
