### ISSUE TITLE
Cannot compile "hello world" code?

### ISSUE THREAD

**Issue by anta40** [zig-lang/zig#607]
I tried to compile the [hello world](http://ziglang.org/#hello_libc) code. Both latest stable built and latest artifact fail:
```
const io = @import("std").io;

pub fn main() -> %void {
    %return io.stdout.printf("Hello, world!\n");
}
```
zig latest stable version:
':\zig-win64-0.1.1\hello.zig:1:30: error: invalid character: '
const io = @import("std").io;

zig latest artifact (0.1.1.336d8189):
C:\zig\hello.zig:1:30: error: invalid carriage return, only '\n' line endings are supported
const io = @import("std").io;

**Comment by jfo** [comment]
That in particular looks like a formatting issue, but those docs are outdated in any case. [This](http://ziglang.org/documentation/master/#hello-world) is closer to current but is also outdated via [this commit](https://github.com/zig-lang/zig/commit/4543413491078c53d24115c5229989cda05cb1a5) from just a few days ago.

A working current example might look like this:

```zig
const io = @import("std").io;

pub fn main() -> %void {
    var stdout_file = %return io.getStdOut();
    var stdout_stream = io.FileOutStream.init(&stdout_file);
    const stdout = &stdout_stream.stream;
    %return stdout.print("Hello, world!\n");
}
``` 
provided the `\c\r` formatting is correct, if I'm understanding the error message.

**Comment by dimenus** [comment]
The latest artifact error message is correct. Zig only supports '\n' line endings. Set your text editor to use Unix line endings.

**Comment by andrewrk** [comment]
On windows, I suggest clicking the most recent green build here: https://ci.appveyor.com/project/andrewrk/zig-d3l86/history?branch=master

Go to Artifacts, and download the .zip file there.

**Comment by andrewrk** [comment]
See #544
