### ISSUE TITLE
allow integer literals to be passed to var args parameters and parameters of type `var`

### ISSUE THREAD

**Issue by dimenus** [zig-lang/zig#623]
consider the following zig code:

```
const std = @import("std");
const debug = std.debug;
const MyEnum = enum {
    Zero,
    One,
    Two,
    Three,
};
pub fn main() -> %void {
    debug.warn("{}\n", @sizeOf(MyEnum));
}
```
fails with: 
`error: parameter of type '(integer literal)' requires comptime`

It would feel much better if 'sizeOf' was defined to either return a u32 or would automatically coerce into the appropriate type rather than having to cast it.

**Comment by andrewrk** [comment]
More generally, we should allow integer literals to be passed to a parameter of type `var`. This is planned.

**Comment by thejoshwolfe** [comment]
How does this work? is the function instantiated for every different literal value?

**Comment by andrewrk** [comment]
That's correct. Also it still doesn't work with var args because of #557. I'm considering fixing it by replacing var args with a tuple type (see #533). Someone on IRC also suggested that tuple types could be implemented in userland if we had `@reflect` and `@reify`.
