### ISSUE TITLE
allow implicit cast from union to its tag type 

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#642]
* implicit cast from tag type of union with comptime known value to union if the payload
   for that field is void
 * implicit cast from union with comptime known value to tag type if the payload for that field is void

```zig
const Letter = enum { A, B, C };
const Value = union(Letter) {
    A: i32,
    B,
    C,
};

fn foo(x: Letter) {

}

test "aoeu" {
    var x: Value = Letter.B;
    foo(x);
}
```

**Comment by PavelVozenilek** [comment]
What is the end goal for this construct (union with exposed tag)? Is it some kind of object support?
 Something like Nim's "object variants"?  ( https://nim-lang.org/docs/manual.html#types-object-variants )


Because I feel  it is feasible to have typesafe union with simple syntax like:

```
const u = union {
  x : i32,
  y : this_type,
  z : that_type,
};

```
