### ISSUE TITLE
passing functions to c causes an assertion failure while compiling

### ISSUE THREAD

**Issue by cenomla** [zig-lang/zig#659]
When a function is passed to c that has `?&void` or `?&const void` as one of the arguments it causes an assertion failure in the compiler:

`zig: /home/cenomla/Workspace/zig/zig/src/analyze.cpp:432: TypeTableEntry* get_maybe_type(CodeGen*, TypeTableEntry*): Assertion 'child_type->type_def' failed.`

If `c_void` is used in place of `void` then zig just crashes without an assertion.

**Comment by andrewrk** [comment]
I fixed the assertion failure, and then added a compile error for using `&void` in a C function because you're supposed to use `&c_void`. This now works for me:

```zig
extern fn foo(ptr: extern fn(?&c_void));

export fn entry() {
    foo(bar);
}

extern fn bar(x: ?&c_void) {

}
```

```
zig build-obj test.zig
```

Let me know if you find another problematic test case.
