### ISSUE TITLE
creating an empty slice causes an assertion

### ISSUE THREAD

**Issue by cenomla** [zig-lang/zig#660]
`zig: /home/cenomla/Workspace/zig/zig/src/codegen.cpp:4306: LLVMOpaqueValue* build_alloca(CodeGen*, TypeTableEntry*, const char*, uint32_t): Assertion 'alignment > 0' failed.`

**Comment by andrewrk** [comment]
what was the source code to trigger this one?

**Comment by cenomla** [comment]
var msg = []u8 {};
_ = stdout.write(msg);
