### ISSUE TITLE
Build problem Ubuntu 16.04

### ISSUE THREAD

**Issue by wilsonk** [zig-lang/zig#708]
Hello all,

I ran into this error when building with llvm-5.0.0 on Ubuntu 16.04 (a clone actually...but close enough). Error:
```
[100%] Linking CXX executable zig
/usr/local/lib/libclangFrontend.a(ASTUnit.cpp.o):(.data.rel+0x0): undefined reference to `llvm::EnableABIBreakingChecks'
```

There were a few 'EnableABIBreakingChecks' errors but they are all similar to the one above. It appears that a workaround for this is to include libLLVMSupport.a, which I did with a simple one-liner include in CMakeLists.txt. Perhaps there is a better solution? Or perhaps I have a weird system and nobody else has run into this error?

In either case, I thought I would mention it so that there is a record of it.

Thanks,
Kelly

**Comment by andrewrk** [comment]
I do want to try to get zig working with the system LLVM that ubuntu provides, but as a data point can you try building with the LLVM 5.0.1 package from http://apt.llvm.org/ instead of the system one?

**Comment by wilsonk** [comment]
Actually, I built 5.0.0 from scratch. I suppose I could try 5.0.1. One minute

**Comment by andrewrk** [comment]
What build options did you use? Anything different than this? https://github.com/zig-lang/zig/wiki/How-to-build-LLVM%2C-libclang%2C-and-liblld-from-source#posix

**Comment by andrewrk** [comment]
Related: #626

**Comment by wilsonk** [comment]
I didn't change any options for building llvm...just 'cmake ../' and go. So it installed to /usr/local, but that shouldn't make any difference from that link, of course.

**Comment by andrewrk** [comment]
In that case I believe this is 5.0.0 / 5.0.1 version mismatch. Zig has a fork of LLD that is on 5.0.1.

**Comment by wilsonk** [comment]
A different error after updating to the recommended clang packages from http://apt.llvm.org


```
Unable to determine libc lib path.
The following command terminated unexpectedly:
./zig build-exe /home/wilsonk/Downloads/zig/src-self-hosted/main.zig --object /home/wilsonk/Downloads/zig/build/zig_cpp/libzig_cpp.a --object /home/wilsonk/Downloads/zig/build/zig_cpp/libembedded_lld_elf.a --object /home/wilsonk/Downloads/zig/build/zig_cpp/libembedded_lld_coff.a --object /home/wilsonk/Downloads/zig/build/zig_cpp/libembedded_lld_lib.a --object /usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.a --cache-dir /home/wilsonk/Downloads/zig/zig-cache --output /home/wilsonk/Downloads/zig/zig-cache/zig --name zig --library c --library LLVM-5.0 --library pthread -isystem /home/wilsonk/Downloads/zig/src -isystem /home/wilsonk/Downloads/zig/build -isystem /usr/lib/llvm-5.0/include --library-path /usr/lib/llvm-5.0/lib 
error: UncleanExit
/usr/local/lib/zig/std/build.zig:593:17: 0x00000000002620dd in ??? (build)
                return error.UncleanExit;
                ^
/usr/local/lib/zig/std/build.zig:1346:9: 0x000000000028941c in ??? (build)
        try builder.spawnChild(zig_args.toSliceConst());
        ^
/usr/local/lib/zig/std/build.zig:1974:9: 0x0000000000250e7a in ??? (build)
        try self.makeFn(self);
        ^
/usr/local/lib/zig/std/build.zig:313:9: 0x0000000000243955 in ??? (build)
        try s.make();
        ^
/usr/local/lib/zig/std/build.zig:307:17: 0x0000000000243906 in ??? (build)
                return err;
                ^
/usr/local/lib/zig/std/build.zig:259:13: 0x000000000023c30e in ??? (build)
            try self.makeOneStep(s);
            ^
/usr/local/lib/zig/std/special/build_runner.zig:124:9: 0x0000000000238244 in ??? (build)
        return err;
        ^

Build failed. Use the following command to reproduce the failure:
./../zig-cache/build ./zig ./.. ./../zig-cache test
```

**Comment by andrewrk** [comment]
What cmake command did you use to configure?

**Comment by wilsonk** [comment]
Woops, yep. That was the problem...I didn't use the correct cmake command. Working now.
