### ISSUE TITLE
Add 0.1.1 to homebrew

### ISSUE THREAD

**Issue by jfo** [zig-lang/zig#714]
https://github.com/jfo/homebrew-core/commit/0f6ad30452eec086d2e34b6b8d781e0dc2c33da9

before I submit a PR to homebrew, here are some issues.

1- the test is very basic, but it follows [their guidelines](https://docs.brew.sh/Formula-Cookbook.html). Should that instead be the full test suite?
2- `-DCMAKE_PREFIX_PATH=/usr/local/opt/llvm@5` feels "works on my machine"-y to me. 
3- `depends_on "llvm@5" => :build` results in a couple of errors on running [`brew audit --new-formula zig`](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md):

```
zig:
  * Dependency 'llvm@5' is an alias; use the canonical name 'llvm'.
  * Dependency 'llvm@5' may be unnecessary as it is provided by macOS; try to build this formula without it.
Error: 2 problems in 1 formula
```
when run with `depends_on "llvm" => :build`, instead

```
zig:
  * Dependency 'llvm' may be unnecessary as it is provided by macOS; try to build this formula without it.
Error: 1 problem in 1 formula
```
Removing that line entirely passes the linter but results in

<details><summary>This</summary>
<p>
<pre>
/usr/bin/sandbox-exec -f /tmp/homebrew20180123-49093-xtphyi.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zig.rb --verbose
==> Downloading https://s3.amazonaws.com/ziglang.org/download/0.1.1/zig-0.1.1.tar.xz
Already downloaded: /Users/jfo/Library/Caches/Homebrew/zig-0.1.1.tar.xz
==> Verifying zig-0.1.1.tar.xz checksum
tar xJf /Users/jfo/Library/Caches/Homebrew/zig-0.1.1.tar.xz
==> cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm@5 -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/zig/0.1.1
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
fatal: Not a git repository (or any of the parent directories): .git
Configuring zig version 0.1.1.
-- Found LLVM: -lLLVMLTO;-lLLVMPasses;-lLLVMObjCARCOpts;-lLLVMSymbolize;-lLLVMDebugInfoPDB;-lLLVMDebugInfoDWARF;-lLLVMMIRParser;-lLLVMCoverage;-lLLVMTableGen;-lLLVMDlltoolDriver;-lLLVMOrcJIT;-lLLVMXCoreDisassembler;-lLLVMXCoreCodeGen;-lLLVMXCoreDesc;-lLLVMXCoreInfo;-lLLVMXCoreAsmPrinter;-lLLVMSystemZDisassembler;-lLLVMSystemZCodeGen;-lLLVMSystemZAsmParser;-lLLVMSystemZDesc;-lLLVMSystemZInfo;-lLLVMSystemZAsmPrinter;-lLLVMSparcDisassembler;-lLLVMSparcCodeGen;-lLLVMSparcAsmParser;-lLLVMSparcDesc;-lLLVMSparcInfo;-lLLVMSparcAsmPrinter;-lLLVMPowerPCDisassembler;-lLLVMPowerPCCodeGen;-lLLVMPowerPCAsmParser;-lLLVMPowerPCDesc;-lLLVMPowerPCInfo;-lLLVMPowerPCAsmPrinter;-lLLVMNVPTXCodeGen;-lLLVMNVPTXDesc;-lLLVMNVPTXInfo;-lLLVMNVPTXAsmPrinter;-lLLVMMSP430CodeGen;-lLLVMMSP430Desc;-lLLVMMSP430Info;-lLLVMMSP430AsmPrinter;-lLLVMMipsDisassembler;-lLLVMMipsCodeGen;-lLLVMMipsAsmParser;-lLLVMMipsDesc;-lLLVMMipsInfo;-lLLVMMipsAsmPrinter;-lLLVMLanaiDisassembler;-lLLVMLanaiCodeGen;-lLLVMLanaiAsmParser;-lLLVMLanaiDesc;-lLLVMLanaiAsmPrinter;-lLLVMLanaiInfo;-lLLVMHexagonDisassembler;-lLLVMHexagonCodeGen;-lLLVMHexagonAsmParser;-lLLVMHexagonDesc;-lLLVMHexagonInfo;-lLLVMBPFDisassembler;-lLLVMBPFCodeGen;-lLLVMBPFDesc;-lLLVMBPFInfo;-lLLVMBPFAsmPrinter;-lLLVMARMDisassembler;-lLLVMARMCodeGen;-lLLVMARMAsmParser;-lLLVMARMDesc;-lLLVMARMInfo;-lLLVMARMAsmPrinter;-lLLVMAMDGPUDisassembler;-lLLVMAMDGPUCodeGen;-lLLVMAMDGPUAsmParser;-lLLVMAMDGPUDesc;-lLLVMAMDGPUInfo;-lLLVMAMDGPUAsmPrinter;-lLLVMAMDGPUUtils;-lLLVMAArch64Disassembler;-lLLVMAArch64CodeGen;-lLLVMAArch64AsmParser;-lLLVMAArch64Desc;-lLLVMAArch64Info;-lLLVMAArch64AsmPrinter;-lLLVMAArch64Utils;-lLLVMObjectYAML;-lLLVMLibDriver;-lLLVMOption;-lLLVMX86Disassembler;-lLLVMX86AsmParser;-lLLVMX86CodeGen;-lLLVMGlobalISel;-lLLVMSelectionDAG;-lLLVMAsmPrinter;-lLLVMDebugInfoCodeView;-lLLVMDebugInfoMSF;-lLLVMX86Desc;-lLLVMMCDisassembler;-lLLVMX86Info;-lLLVMX86AsmPrinter;-lLLVMX86Utils;-lLLVMMCJIT;-lLLVMLineEditor;-lLLVMInterpreter;-lLLVMExecutionEngine;-lLLVMRuntimeDyld;-lLLVMCodeGen;-lLLVMTarget;-lLLVMCoroutines;-lLLVMipo;-lLLVMInstrumentation;-lLLVMVectorize;-lLLVMScalarOpts;-lLLVMLinker;-lLLVMIRReader;-lLLVMAsmParser;-lLLVMInstCombine;-lLLVMTransformUtils;-lLLVMBitWriter;-lLLVMAnalysis;-lLLVMProfileData;-lLLVMObject;-lLLVMMCParser;-lLLVMMC;-lLLVMBitReader;-lLLVMCore;-lLLVMBinaryFormat;-lLLVMSupport;-lLLVMDemangle;-lcurses;-lz;-lm  
-- Found CLANG: /usr/local/opt/llvm@5/lib/libclangFrontend.a;/usr/local/opt/llvm@5/lib/libclangDriver.a;/usr/local/opt/llvm@5/lib/libclangSerialization.a;/usr/local/opt/llvm@5/lib/libclangSema.a;/usr/local/opt/llvm@5/lib/libclangAnalysis.a;/usr/local/opt/llvm@5/lib/libclangAST.a;/usr/local/opt/llvm@5/lib/libclangParse.a;/usr/local/opt/llvm@5/lib/libclangSema.a;/usr/local/opt/llvm@5/lib/libclangBasic.a;/usr/local/opt/llvm@5/lib/libclangEdit.a;/usr/local/opt/llvm@5/lib/libclangLex.a  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/build
==> make install
Scanning dependencies of target embedded_lld_coff
Scanning dependencies of target embedded_softfloat
Scanning dependencies of target embedded_lld_lib
[  0%] Building CXX object CMakeFiles/embedded_lld_coff.dir/deps/lld/COFF/DLL.cpp.o
[  1%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/8086/f128M_isSignalingNaN.c.o
[  2%] Building CXX object CMakeFiles/embedded_lld_lib.dir/deps/lld/lib/Driver/DarwinLdDriver.cpp.o
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/COFF/DLL.cpp:21:
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/COFF/Chunks.h:13:
/tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/COFF/Config.h:13:10: fatal error: 'llvm/ADT/StringRef.h' file not found
#include "llvm/ADT/StringRef.h"
         ^~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/lib/Driver/DarwinLdDriver.cpp:16:
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/include/lld/Core/ArchiveLibraryFile.h:13:
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/include/lld/Core/File.h:13:
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/include/lld/Core/AbsoluteAtom.h:13:
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/include/lld/Core/Atom.h:13:
/tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/include/lld/Core/LLVM.h:20:10: fatal error: 'llvm/ADT/Hashing.h' file not found
#include "llvm/ADT/Hashing.h"
         ^~~~~~~~~~~~~~~~~~~~
[  2%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/8086/s_commonNaNToF128M.c.o
Scanning dependencies of target embedded_lld_elf
[  2%] Building CXX object CMakeFiles/embedded_lld_elf.dir/deps/lld/ELF/ScriptLexer.cpp.o
[  3%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/8086/s_commonNaNToF32UI.c.o
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/ELF/ScriptLexer.cpp:35:
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/ELF/ScriptLexer.h:13:
/tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/include/lld/Core/LLVM.h:20:10: fatal error: 'llvm/ADT/Hashing.h' file not found
#include "llvm/ADT/Hashing.h"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/embedded_lld_coff.dir/deps/lld/COFF/DLL.cpp.o] Error 1
make[1]: *** [CMakeFiles/embedded_lld_coff.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  3%] Building CXX object CMakeFiles/embedded_lld_lib.dir/deps/lld/lib/Config/Version.cpp.o
[  3%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/8086/s_commonNaNToF64UI.c.o
1 error generated.
make[2]: *** [CMakeFiles/embedded_lld_elf.dir/deps/lld/ELF/ScriptLexer.cpp.o] Error 1
make[1]: *** [CMakeFiles/embedded_lld_elf.dir/all] Error 2
[  4%] Building CXX object CMakeFiles/embedded_lld_lib.dir/deps/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp.o
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/lib/Config/Version.cpp:14:
/tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/include/lld/Config/Version.h:18:10: fatal error: 'llvm/ADT/StringRef.h' file not found
#include "llvm/ADT/StringRef.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/embedded_lld_lib.dir/deps/lld/lib/Config/Version.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  4%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/8086/s_f128MToCommonNaN.c.o
[  5%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/8086/s_f32UIToCommonNaN.c.o
1 error generated.
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp:10:
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/include/lld/Core/AbsoluteAtom.h:13:
In file included from /tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/include/lld/Core/Atom.h:13:
/tmp/zig-20180123-49095-1fmj1y/zig-0.1.1/deps/lld/include/lld/Core/LLVM.h:20:10: fatal error: 'llvm/ADT/Hashing.h' file not found
#include "llvm/ADT/Hashing.h"
         ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/embedded_lld_lib.dir/deps/lld/lib/Driver/DarwinLdDriver.cpp.o] Error 1
[  5%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/8086/s_f64UIToCommonNaN.c.o
[  6%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/8086/s_propagateNaNF128M.c.o
[  6%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/8086/softfloat_raiseFlags.c.o
[  7%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_add.c.o
[  7%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_div.c.o
[  8%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_eq.c.o
[  8%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_eq_signaling.c.o
[  9%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_le.c.o
[  9%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_le_quiet.c.o
1 error generated.
make[2]: *** [CMakeFiles/embedded_lld_lib.dir/deps/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp.o] Error 1
make[1]: *** [CMakeFiles/embedded_lld_lib.dir/all] Error 2
[ 10%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_lt.c.o
[ 10%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_lt_quiet.c.o
[ 10%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_mul.c.o
[ 11%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_mulAdd.c.o
[ 11%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_rem.c.o
[ 12%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_roundToInt.c.o
[ 12%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_sqrt.c.o
[ 13%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_sub.c.o
[ 13%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_to_f16.c.o
[ 14%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_to_f32.c.o
[ 14%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_to_f64.c.o
[ 15%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_to_i32.c.o
[ 15%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_to_i32_r_minMag.c.o
[ 15%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_to_i64.c.o
[ 16%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_to_i64_r_minMag.c.o
[ 16%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_to_ui32.c.o
[ 17%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_to_ui32_r_minMag.c.o
[ 17%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_to_ui64.c.o
[ 18%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f128M_to_ui64_r_minMag.c.o
[ 18%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f32_to_f128M.c.o
[ 19%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/f64_to_f128M.c.o
[ 19%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_add256M.c.o
[ 20%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_addCarryM.c.o
[ 20%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_addComplCarryM.c.o
[ 21%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_addF128M.c.o
[ 21%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_addM.c.o
[ 21%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_addMagsF16.c.o
[ 22%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_addMagsF32.c.o
[ 22%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_addMagsF64.c.o
[ 23%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_approxRecip32_1.c.o
[ 23%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_approxRecipSqrt32_1.c.o
[ 24%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_approxRecipSqrt_1Ks.c.o
[ 24%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_approxRecip_1Ks.c.o
[ 25%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_compare128M.c.o
[ 25%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_compare96M.c.o
[ 25%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_countLeadingZeros32.c.o
[ 26%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_countLeadingZeros16.c.o
[ 27%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_countLeadingZeros64.c.o
[ 27%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_countLeadingZeros8.c.o
[ 27%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_eq128.c.o
[ 28%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_invalidF128M.c.o
[ 28%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_isNaNF128M.c.o
[ 29%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_le128.c.o
[ 29%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_lt128.c.o
[ 30%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_mul128MTo256M.c.o
[ 30%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_mul64To128M.c.o
[ 31%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_mulAddF128M.c.o
[ 31%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_mulAddF16.c.o
[ 32%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_mulAddF32.c.o
[ 32%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_mulAddF64.c.o
[ 33%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_negXM.c.o
[ 33%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_normRoundPackMToF128M.c.o
[ 33%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_normRoundPackToF16.c.o
[ 34%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_normRoundPackToF32.c.o
[ 34%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_normRoundPackToF64.c.o
[ 35%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_normSubnormalF128SigM.c.o
[ 35%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_normSubnormalF16Sig.c.o
[ 36%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_normSubnormalF32Sig.c.o
[ 36%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_normSubnormalF64Sig.c.o
[ 37%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_remStepMBy32.c.o
[ 37%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_roundMToI64.c.o
[ 38%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_roundMToUI64.c.o
[ 38%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_roundPackMToF128M.c.o
[ 39%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_roundPackToF16.c.o
[ 39%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_roundPackToF32.c.o
[ 39%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_roundPackToF64.c.o
[ 40%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_roundToI32.c.o
[ 40%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_roundToI64.c.o
[ 41%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_roundToUI32.c.o
[ 41%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_roundToUI64.c.o
[ 42%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shiftLeftM.c.o
[ 42%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shiftNormSigF128M.c.o
[ 43%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shiftRightJam256M.c.o
[ 43%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shiftRightJam32.c.o
[ 44%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shiftRightJam64.c.o
[ 44%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shiftRightJamM.c.o
[ 45%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shiftRightM.c.o
[ 45%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shortShiftLeft64To96M.c.o
[ 45%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shortShiftLeftM.c.o
[ 46%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shortShiftRightExtendM.c.o
[ 46%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shortShiftRightJam64.c.o
[ 47%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shortShiftRightJamM.c.o
[ 47%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_shortShiftRightM.c.o
[ 48%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_sub1XM.c.o
[ 48%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_sub256M.c.o
[ 49%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_subMagsF16.c.o
[ 50%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_subM.c.o
[ 50%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_subMagsF32.c.o
[ 50%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_subMagsF64.c.o
[ 51%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/s_tryPropagateNaNF128M.c.o
[ 51%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/softfloat_state.c.o
[ 51%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/ui32_to_f128M.c.o
[ 52%] Building C object CMakeFiles/embedded_softfloat.dir/deps/SoftFloat-3d/source/ui64_to_f128M.c.o
[ 52%] Linking C static library libembedded_softfloat.a
[ 52%] Built target embedded_softfloat
make: *** [all] Error 2

==> Formula
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zig.rb
==> Configuration
HOMEBREW_VERSION: 1.5.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: ace2d569dcd3a45d0fc49a6742540b6f7a957fbc
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0f6ad30452eec086d2e34b6b8d781e0dc2c33da9
Core tap last commit: 8 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_ENABLE_AUTO_UPDATE_MIGRATION: 1
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/jfo/.rvm/rubies/ruby-2.4.1/bin/ruby
Java: 9.0.1, 1.8.0_152
macOS: 10.13.2-x86_64
Xcode: 9.1
CLT: 9.2.0.0.1.1510905681
X11: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/cmake/bin:/usr/bin:/bin:/usr/sbin:/sbin

Logs:
     /Users/jfo/Library/Logs/Homebrew/zig/00.options.out
     /Users/jfo/Library/Logs/Homebrew/zig/01.cmake.cc
     /Users/jfo/Library/Logs/Homebrew/zig/01.cmake
     /Users/jfo/Library/Logs/Homebrew/zig/02.make.cc
     /Users/jfo/Library/Logs/Homebrew/zig/02.make
READ THIS: https://docs.brew.sh/Troubleshooting.html
</pre>
</p>
</details>
<br>

Note it might e my xcode outdatedness but that shouldn't matter, it builds normally with the annotation.

There are some todos here: this just adds the tarball version of the 0.1.1 release. It could also add a nightly or master from the github repo directly. You could have a prebuilt binary (I think that one's called a bottle.)

This is a good place to start though. LMKYT.

**Comment by andrewrk** [comment]
> 2- -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm@5 feels "works on my machine"-y to me.

I think you can replace `/usr/local/opt` with `#{prefix}`.

> 3- depends_on "llvm@5" => :build results in a couple of errors on running brew audit --new-formula zig:

I believe both of those errors from `brew audit` are false positives.
 * We definitely want to version lock to depend on `llvm@5` otherwise the zig package will break when `llvm` becomes aliased to `llvm@6`.
 * The llvm dependency is for sure necessary. The LLVM that is provided by macOS is not compatible with zig.

I suggest making the 1 above suggestion, go ahead and make the pull request to homebrew, and let the homebrew maintainers provide feedback from there.

**Comment by jfo** [comment]
Sgtm. I'll test and submit tomorrow.

Also feel free to suggest a better desc.

**Comment by andrewrk** [comment]
My suggestion:  "A programming language designed for robustness, optimality, and clarity"

**Comment by jfo** [comment]
Brew imposes no indefinite article at the beginning of the desc (I tried
that one)

**Comment by andrewrk** [comment]
"programming language designed for robustness, optimality, and clarity"

**Comment by jfo** [comment]
@andrewrk it occurs to me to ask if `llvm@5` is a build time dep only. I think what I've got currently specifies it as such, not sure exactly how brew resolves those deps but I assume this will come up in the discussion.

**Comment by jfo** [comment]
nm I think that issue is resolved.

https://github.com/Homebrew/homebrew-core/pull/23189#discussion_r163258500

**Comment by andrewrk** [comment]
It looks like the Homebrew issue is waiting for you to remove `:build`

**Comment by jfo** [comment]
I've done that

https://github.com/Homebrew/homebrew-core/pull/23189/commits/3292741e9e917216b7fecb2fc2a699763f305c85#diff-39846aeb14d767ac7a151b79c8a8e67bR8

**Comment by andrewrk** [comment]
Looks good now. The maintainer added "ready to merge" and approved it.

**Comment by jfo** [comment]
Resolved in https://github.com/Homebrew/homebrew-core/commit/c33c6222df4c976f685087cdc382ed9874c09314

**Comment by andrewrk** [comment]
FYI the labels "proposal", "accepted", "rejected" are for zig language design decisions.

**Comment by jfo** [comment]
Ok good to know.  :+1:
