### ISSUE TITLE
Update readme / website to include homebrew installation instructions

### ISSUE THREAD

**Issue by jfo** [zig-lang/zig#717]
`brew install zig` installs 0.1.1. Yay! 

That information should be accessible somewhere. I'm opening an issue because I don't know exactly where it should go.

**Comment by andrewrk** [comment]
how about on this page? http://ziglang.org/download/

**Comment by jfo** [comment]
![image](https://user-images.githubusercontent.com/4204764/35342915-97b1aafc-0129-11e8-8ac5-ebb7eb2095a7.png)

**Comment by jfo** [comment]
![image](https://user-images.githubusercontent.com/4204764/35343141-27b0423a-012a-11e8-89d0-faaa54b746e7.png)

**Comment by jfo** [comment]
![image](https://user-images.githubusercontent.com/4204764/35343215-56f1b416-012a-11e8-8b46-ef65de9ad7a0.png)

**Comment by jfo** [comment]
also related [try this](https://gist.github.com/f963e8771b42be59b9e5f930a85829cf) if you're so inclined. I'm 6/10 generally, 2/10 specifically on that diff.

**Comment by andrewrk** [comment]
cool I'll have a look. also in the future feel free to make a PR directly to https://github.com/zig-lang/www.ziglang.org

**Comment by jfo** [comment]
Sure, I did it here b/c the readme there said the 'docs are generated over here' and I misunderstood that to mean the whole site.

Since no one would like, write html by hand these days, surely, right?? :smile:

I'll move this issue.
