### ISSUE TITLE
Can't pass non-nullable pointer to nullable

### ISSUE THREAD

**Issue by tjpalmer** [zig-lang/zig#731]
Seems like this should be allowed as implicitly compatible (of course, not the other way around):

```
D:\Workspace\beast\src\main.zig:120:34: error: expected type '?&const ?&const u8', found '&const &const u8'
    c.glShaderSource(shader, 1, &sources, &sizes);
```

**Comment by tjpalmer** [comment]
Maybe it's the nested pointer risk in case the callee wanted to change things? But they are const in this case, so seems like it should be presumed safe.

**Comment by tjpalmer** [comment]
Moved some code to a separate file, and then this error popped up, too:

```
D:\Workspace\beast\src\main.zig:29:29: error: expected type '?&struct_SDL_Window', found '&struct_SDL_Window'
  c.SDL_GL_SwapWindow(window.window);
                            ^
D:\Workspace\beast\src\main.zig:46:39: error: expected type '?&struct_SDL_Window', found '&struct_SDL_Window'
            c.SDL_GL_SwapWindow(window.window);
```

It wasn't previously causing this error, so something subtle might be going on, and it might be related to the original error report above, since it's about non-null to null, again. And no nested pointers here, so that should be an issue in this case either.

**Comment by andrewrk** [comment]
I'll get these fixed soon. In the meantime, a workaround is using `@ptrCast`. It should work even with nullable pointers.

**Comment by andrewrk** [comment]
Is your code open source by any chance? So that I could try to repro these bugs?

**Comment by tjpalmer** [comment]
It's in this repo: https://github.com/tjpalmer/beast

The second case above was happening when the code was in main.

**Comment by andrewrk** [comment]
Thanks! I'll have a look. Unrelated to this bug, one thing I would recommend is to have only a single `@cImport` in your entire program. The reason for having multiple is advanced, for situations where, in C, you would want to compile different .o files with different preprocessor defines, or something like this.

**Comment by tjpalmer** [comment]
I had them separate so I could more easily relate dependencies and encapsulate. (This code is also early and on limited time, so don't presume everything there is on purpose, though.) So I understand better, what are the reasons for a single @cImport?

**Comment by andrewrk** [comment]
I added to the docs to answer this: http://ziglang.org/documentation/master/#cImport
