### ISSUE TITLE
Add an 'ignore' expression that explicitly ignores error values

### ISSUE THREAD

**Issue by zesterer** [zig-lang/zig#735]
I think the usefulness is fairly obvious.

Currently, the `fallible();` causes a compilation error if `fallible` returns an error-or value. It should be possible to explicitly ignore this error in cases where we don't care whether an error occurred like `ignore fallible();`.

**Comment by andrewrk** [comment]
`fallible() catch {}`

**Comment by thejoshwolfe** [comment]
`catch` as it's currently implemented shows control flow moving from left to right. We want the `catch` body to be syntactically after the errorable expression. If the `catch` body is empty, then you're ignoring the error.

There are certainly exceptions to the "execution from left to right" rule, such as `=` and `try`. But since `catch` already makes sense as it is, we should stick with it as the one obvious way to ignore an error.

**Comment by zesterer** [comment]
Fair enough. That's a well-justified position.

**Comment by gshanemiller** [comment]
Seconding this: consider this code:

```
pub fn myprint() !void {                                                                                   
  const stdout = std.io.getStdOut().writer();                                                                                                                                                                                                   
  try std.fmt.format(stdout, "hello world\n", .{});                                                                               
}

pub fn main() u8 {                                                                                                      
  myprint() catch |err| {                                                                                              
  // how in the heck do I ignore 'err' without changing 
  // the return type of the outer function here 'main'?
  // it is seriously annoying to be dragged into this to
  // just print something to stdout. 
  };
```

To be clear: the catch following 'myprint()' is good; I just don't know how to ignore 'err' without the compiler giving an another error 'unused capture'.

**Comment by nektro** [comment]
the suggestion above works. the issue is your `main` returning `u8`. you can either change the return of `main` to `void` or add `return 0;` after the call to `myprint() catch {};`

**Comment by gshanemiller** [comment]
>the issue is your main returning u8
Yah but I wrote I do **NOT** wanna change the return type. Right? because that solution tends to require changing the return types all the way up the call stack. At some point a function needs to return type T **not** T? or void!T otherwise code becomes littered with pigeon dropping code. Which was my original complaint.

**Comment by Srekel** [comment]
So I just hit upon this and I'm not sure why it's not allowed to explicitly discard an error. Here's what happened:

```ts
    pub fn doesAssetExist(self: AssetManager, id: IdLocal) bool {
        _ = self;
        std.fs.cwd().access(&id.str, .{ .mode = .read_only }) catch {
            return false;
        };
        return true;
    }
```

This was returning false for all my files. I wasn't sure why, so I wanted to see what the error was:
```
    pub fn doesAssetExist(self: AssetManager, id: IdLocal) bool {
        _ = self;
        std.fs.cwd().access(&id.str, .{ .mode = .read_only }) catch |err| {
            _ = err;
            return false;   <------- breakpoint here
        };
        return true;
    }
```

But this doesn't compile - error is discarded. 

This worked but is more cumbersome.

```ts
    pub fn doesAssetExist(self: AssetManager, id: IdLocal) bool {
        _ = self;
        std.fs.cwd().access(&id.str, .{ .mode = .read_only }) catch |err| {
            std.log.debug("{}", .{err});
            return false;
        };
        return true;
    }
```

(in the end the error was that it was invalid utf8, in my case I needed `id.toString()` )

**Comment by silversquirl** [comment]
@Srekel you can `catch` an error value just fine: `error.Foo catch {}`

So in your `catch |err|` you'd just add an explicit `err catch {}` to discard the value. It's possible LLVM would then optimize it out though, so you might need to use something like `std.mem.doNotOptimizeAway` anyway if you want to see it in a debugger

**Comment by Srekel** [comment]
Ah I see, I didn't know that, thanks. :)  

However, I'm willing to bet that me in six months will have forgotten and will again assume that `_ = x` is de facto way to explicitly discard things you're not interested in. (sorry, I don't mean to sound snarky - just trying to point out that it is a perfectly reasonable thing to expect to work. )
