### ISSUE TITLE
'export' does not compile function if function is not called by other Zig code

### ISSUE THREAD

**Issue by zesterer** [zig-lang/zig#749]
I have a function called by assembly code (i.e: Zig is not implicitly aware that it is in use). The `export` keyword applied to the function does not make the function compile, nor does it export the function symbol in the resulting object file.

**Comment by andrewrk** [comment]
my guess is that the file is not getting imported. note that all top level declarations are lazy, including variable declarations that include `@import` expressions.

So you could, for instance, do this:

```zig
comptime {
    _ = @import("file_with_exports.zig");
}
```

or put your exports in the root source file.

**Comment by zesterer** [comment]
That syntax doesn't appear to work either, unfortunately. The lazy evaluation seems to prevent the function ever being exported, despite the `export` keyword (I'd consider this a bug: `export` *implies* that external code will use it).

**Comment by andrewrk** [comment]
can you push it to a branch so I can look at it?

**Comment by zesterer** [comment]
Here you go: https://github.com/tupai-os/kernel/tree/kearly-undefined

**Comment by zesterer** [comment]
What. I could have sworn I added `export`... Oh well. My mistake. A case of idiocy, it seems.

**Comment by andrewrk** [comment]
no worries! happy to help.
