### ISSUE TITLE
Is `zig version` accurate?

### ISSUE THREAD

**Issue by jfo** [zig-lang/zig#757]
```shell
~/code/zig/build (master) $ git rev-parse --short HEAD
dd20f558
~/code/zig/build (master) $ make install
...
~/code/zig/build (master) $ which zig
/Users/jfo/code/zig/build/zig
~/code/zig/build (master) $ zig version
0.1.1.44d8d654
~/code/zig/build (master) $
```

**Comment by andrewrk** [comment]
It's accurate from a clean build, which is what we do for releases and appveyor artifacts. I'm happy to have the sha1 version be stale when doing local development, otherwise I'd have to rebuild every file when I make a commit.

**Comment by jfo** [comment]
That makes sense, although if there was a way to mark it as `dirty` or something it would be helpful to have it articulated exactly what 'version' I'm using at any particular time. That might be more unpossible than it is worth though.

And I [see what you mean](https://github.com/jfo/zig/blob/dd20f558f0b3740a37c1d16a306e35f8cbe6a38f/src/config.h.in#L14) wrt where the version string actually comes from. 

This answers my question.
