### ISSUE TITLE
@field builtin function to do field access with a comptime string as the field name

### ISSUE THREAD

**Issue by Hejsil** [zig-lang/zig#766]
Add following builtin function:
```
@memberTag(comptime T: type, index: usize) -> (error set or enum value from T)
```

Example of how it works:
```
@memberTag(enum { A, B, C }, 1) // returns B
@memberTag(error { D, E, F }, 1) // returns E
```

Idk what the use case is for having it work for enums, but the use case for error sets was mentioned [here](https://github.com/zig-lang/zig/issues/632#issuecomment-350202865).

**Comment by andrewrk** [comment]
Now that I think of it, I think this is accomplished by:

```
@field(T, @memberName(T, index))
```

So I'll implement `@field` instead.
