### ISSUE TITLE
std.fmt.format does not accept literal values

### ISSUE THREAD

**Issue by jacobdufault** [zig-lang/zig#775]
Example:

```zig
const std = @import("std");

pub fn main() !void {
  var stdout_file = try std.io.getStdOut();
  var stdout_file_stream = std.io.FileOutStream.init(&stdout_file);
  try stdout_file_stream.stream.print("{}\n", 3);
}
```

error:
```
main.zig:32:47: error: parameter of type '(integer literal)' requires comptime
```

This is useful because the 3 could be coming from a comptime variable.

It seems I can work around this by wrapping it in a variable, ie,

```zig
var i: i32 = 3;
stdout_file_stream.stream.print("{}\n", i);
```

but that is very ugly.

**Comment by jfo** [comment]
This is being addressed, see https://github.com/zig-lang/zig/issues/747, so I'm closing as duplicate. Thanks for the report though!
