### ISSUE TITLE
Non-pub members are accessible outside of std.

### ISSUE THREAD

**Issue by jacobdufault** [zig-lang/zig#805]
Non-pub members are accessible outside of std. For example, this is done in the hello world example.

example:
https://github.com/zig-lang/zig/blob/101b7745c4da1fdf0ebe723710fe8b195013fc0e/example/hello_world/hello.zig#L4-L8

https://github.com/zig-lang/zig/blob/101b7745c4da1fdf0ebe723710fe8b195013fc0e/std/os/file.zig#L302-L310

https://github.com/zig-lang/zig/blob/101b7745c4da1fdf0ebe723710fe8b195013fc0e/std/io.zig#L30-L38

**Comment by andrewrk** [comment]
Thanks for the report. I believe this is #569
