### ISSUE TITLE
Fails to build andrewrk/clashos with 0.1.1

### ISSUE THREAD

**Issue by berkus** [zig-lang/zig#822]
```
λ git clone git@github.com:andrewrk/clashos.git
λ cd clashos
λ zig build
/usr/local/Cellar/zig/0.1.1/lib/zig/std/special/build_runner.zig:82:15: error: expression value is ignored
    root.build(&builder);
              ^
/usr/local/Cellar/zig/0.1.1/lib/zig/std/special/build_runner.zig:99:19: error: expression value is ignored
        root.build(builder);
```

Dunno, if this is zig or clashos problem; but looks like something in std build runner?

**Comment by tiehuis** [comment]
That repository is tracking the latest master version of git. `0.1.1` was released on November 2nd so the following commit should be the latest as of then. Unsure however if this was up to date as of `0.1.1` but if not it should be closer.

https://github.com/andrewrk/clashos/commit/9b452d877ad3ddd8e04fd2ff26146260ada4e46a

You can try the following to see:

```
git checkout 9b452d877ad3ddd8e04fd2ff26146260ada4e46a
zig build
```

**Comment by berkus** [comment]
Hmm, let me try that.

What's the zig version of master? I can try installing that too. Does it have something similar to `rustup nightly`? :)

**Comment by tiehuis** [comment]
Currently you need to compile it from source. It isn't too hard to do that but you will need to get llvm6.0 which is pretty recent. You can build this from source (it will take a fair while however) if you follow this https://github.com/zig-lang/zig/wiki/How-to-build-LLVM%2C-libclang%2C-and-liblld-from-source.

If you let me know your operating system/distribution though I can let you know if there are any quicker shortcuts.

**Comment by berkus** [comment]
Yeah I was planning to `brew install --HEAD llvm` today anyway, I'll update you how it goes.

**Comment by andrewrk** [comment]
Feel free to re-open an issue in the ClashOS project if you run into further issues.

**Comment by berkus** [comment]
Ok, it failed to build with LLVM 7.0 btw, so I'm waiting for GA of 6.0 in brew and will try again.

**Comment by andrewrk** [comment]
https://github.com/Homebrew/homebrew-core/pull/25012

I'll get the llvm7 branch in zig going too. But recommended is master branch with llvm 6.
