### ISSUE TITLE
Feature request: update the SoftFloat library to release 3e

### ISSUE THREAD

**Issue by data-man** [zig-lang/zig#823]
The changelog (2018 January 20):

>Changed the default numeric code for optional rounding mode odd (round to odd, also known as jamming) from 5 to 6.
>
>Modified the behavior of rounding mode odd when rounding to an integer value (either conversion to an integer format or a ‘roundToInt’ function). Previously, for those cases only, rounding mode odd acted the same as rounding to minimum magnitude. Now all operations are rounded consistently.
>
>Fixed some errors in the specialization code modeling Intel x86 floating-point, specifically the integers returned on invalid operations and the propagation of NaN payloads in a few rare cases.
>
>Added specialization code modeling ARM floating-point, conforming to VFPv2 or later.
>
>Added an example target for ARM processors.
>
>Fixed a minor bug whereby function f16_to_ui64 might return a different integer than expected in the case that the floating-point operand is negative.
>
>Added example target-specific optimization for GCC, employing GCC instrinsics and support for 128-bit integer arithmetic.
>
>Made other minor improvements.

**Comment by data-man** [comment]
So fast! Thanks!

**Comment by andrewrk** [comment]
![gotta-go-fast2](https://user-images.githubusercontent.com/106511/37231029-95eb9cfe-23b7-11e8-954a-4724a00c5ede.png)
