### ISSUE TITLE
Accessing Environment Variables

### ISSUE THREAD

**Issue by runeimp** [zig-lang/zig#841]
Firstly I love the concepts behind Zig and just started playing with it yesterday. Very promising!

I'm trying to devise a good example for pulling environment variables. I've come up with the following thus far.

```javascript
const std = @import("std");

pub fn main() !void {
    const allocator = std.debug.global_allocator;
    const env_map = std.os.getEnvMap(allocator) catch unreachable;
    const env_vars = &std.BufMap(env_map);
    const msg_format = "Hello, {}!\n";
    const name = env_vars.get("HELLO");
    const stdout = &(std.io.FileOutStream.init(&(try std.io.getStdOut())).stream);

    if (name != null) {
        try stdout.print(msg_format, name);
    } else {
        try stdout.print(msg_format, "world");
    }
}
```

But this seems horribly verbose but was the best I could manage to get through all the type errors. I believe this has much to do with #731 and other similar issues. But maybe I'm just overlooking something as well. Once I get a better understanding of some of these type issues I'd be happy to contribute updates to the docs.  😃

**Comment by andrewrk** [comment]
Here are some suggestions:

```diff
-    const env_map = std.os.getEnvMap(allocator) catch unreachable;
+    const env_map = try std.os.getEnvMap(allocator);
```

```diff
-    const msg_format = "Hello, {}!\n";
-    if (name != null) {
-        try stdout.print(msg_format, name);
-    } else {
-        try stdout.print(msg_format, "world");
-    }
+    try stdout.print("Hello, {}!\n", name ?? "world");
```

```diff
-    const env_map = std.os.getEnvMap(allocator) catch unreachable;
-    const env_vars = &std.BufMap(env_map);
-    const name = env_vars.get("HELLO");
+    const name = std.os.getEnvVarOwned(allocator, "HELLO");
+    defer allocator.free(name);
```

The OS-agnostic environment variable API requires an allocator due to
the Windows API. If you are only targeting POSIX you can use
`std.os.getEnvPosix` which does not require an allocator.

**Comment by runeimp** [comment]
Thanks for the suggestions! That all looks much nicer. But...

```bash
$ zig version
0.2.0.
$ zig build-exe hello_env.zig
/Users/runeimp/dev/hello/zig/hello_env.zig:11:38: error: expected nullable type, found '@typeOf(getEnvVarOwned).ReturnType.ErrorSet![]u8'
    try stdout.print("Hello, {}!\n", name ?? "world");
                                     ^
/usr/local/Cellar/zig/0.2.0/lib/zig/std/mem.zig:113:35: error: invalid cast from type '@typeOf(getEnvVarOwned).ReturnType.ErrorSet![]u8' to '[]const u8'
        const bytes = ([]const u8)(memory);
                                  ^
/Users/runeimp/dev/hello/zig/hello_env.zig:7:25: note: called from here
    defer allocator.free(name);
                        ^
```
These are much like the errors I was getting before I came up with the code I posted earlier. This on OS X 10.11.6 El Capitan with zig installed via Homebrew. Also `/Users/runeimp/dev` is symlinked to `/Users/runeimp/Dropbox/UserENV/Profile/dev`. Might any of that be part of the issue?

**Comment by andrewrk** [comment]
Oops, my example code did not handle the error from `getEnvVarOwned`. You want to use `try` in front of it:

```zig
    const name = try std.os.getEnvVarOwned(allocator, "HELLO");
```

**Comment by runeimp** [comment]
Almost there...  👼 

```bash
$ zig build-exe hello_env.zig
/Users/runeimp/dev/hello/zig/hello_env.zig:11:38: error: expected nullable type, found '[]u8'
    try stdout.print("Hello, {}!\n", name ?? "world");
                                     ^
```
The type errors seem very hard to avoid. Seems like there is a basic concept of byte types, slices, string literals, and other string like things management I'm just not grasping in this language yet.

**Comment by andrewrk** [comment]
Have a look through the docs: https://ziglang.org/documentation/master/

Feel free to ask questions on IRC, or message the email list if you need help.

**Comment by runeimp** [comment]
I've been pouring over the docs since yesterday. They are lacking significantly in how to deal with type conversion. This is understandable with the language being so young. And is why I was offering to help with the docs once I was able to understand the expected methodology for handling what in any higher level language would simply be strings. The fact that it was not a simple matter to work out just accessing environment variables shows a pretty significant weakness in the language as it stands. I've done this sort of exercise with many languages including C, D, Go, and Rust and have never had so much trouble just accessing and printing an environment variable. Are there specific sections I should review in the docs that I may be overlooking? Or are you referencing the Casting section which has nothing but TODO notes?

I'm sorry if I'm sounding antagonistic. I really like what your doing with Zig and where it could be in a year's time is very exciting. But currently the methodology for handling the multitude of type conversion situations (how to cast, how to handle casting errors, why a variable set to `[]u8` can't hold `[5]u8`, `const []u8`, and especially `&?const []u8` data, etc.) that are necessary to manage textual data is very confusing. The fact that all the functions I've tried that return textual data use different types makes it very difficult. I believe you've already mentioned creating a Zig by Example site. I look forward to that happening. Finish the Casting section of the docs would be a huge benefit to me in the meantime.

Thank you for all the time I'm sure was put into this project. I hope it is very successful and I look forward to learning more about it.

**Comment by andrewrk** [comment]
`expected nullable type, found '[]u8'`

`??` unwraps a nullable value. If you get this error, the type is not nullable.

> Are there specific sections I should review in the docs that I may be overlooking? 

This one: https://ziglang.org/documentation/master/#Nullables

It's important to understand types and what they mean, since types are the main safety feature in zig protecting us from memory corruption and other bugs like this.

Casting is a glaring hole in the documentation. I'll try to get to it soon. #367

**Comment by runeimp** [comment]
Wow, COVID-19 killed my ability to keep up with other languages at all. Thanks for the updates @milahu and @praschke! Hopefully I'll have some free time to play with Zig again soon. 😀

**Comment by loftafi** [comment]
This is one of the results that appears in search engines when I search for help on how to use this. Apparently this causes a panic in zig 0.14.1, at least on Mac where I am using it. So it might not be available on all platforms:

```zig
var current = try std.process.getEnvMap(allocator);
```

It causes the following on MacOS Sequoia 15.5:

```zig
thread 24507038 panic: incorrect alignment
/Volumes/zig/zig-aarch64-macos-0.14.1/lib/std/heap/SmpAllocator.zig:137:34: 0x1005ce3c3 in alloc (git_backup)
            const node: *usize = @ptrFromInt(top_free_ptr);
                                 ^
/Volumes/zig/zig-aarch64-macos-0.14.1/lib/std/mem/Allocator.zig:129:26: 0x10055e7e7 in allocBytesWithAlignment__anon_12470 (git_backup)
    return a.vtable.alloc(a.ptr, len, alignment, ret_addr);
                         ^
/Volumes/zig/zig-aarch64-macos-0.14.1/lib/std/mem/Allocator.zig:263:40: 0x10054c9eb in allocWithSizeAndAlignment__anon_10544 (git_backup)
    return self.allocBytesWithAlignment(alignment, byte_count, return_address);
                                       ^
/Volumes/zig/zig-aarch64-macos-0.14.1/lib/std/mem/Allocator.zig:257:75: 0x10052d8b7 in alloc__anon_8627 (git_backup)
    const ptr: [*]align(a) T = @ptrCast(try self.allocWithSizeAndAlignment(@sizeOf(T), a, n, return_address));
                                                                          ^
/Volumes/zig/zig-aarch64-macos-0.14.1/lib/std/mem/Allocator.zig:423:40: 0x10052d6fb in dupe__anon_8621 (git_backup)
    const new_buf = try allocator.alloc(T, m.len);
                                       ^
/Volumes/zig/zig-aarch64-macos-0.14.1/lib/std/process.zig:214:44: 0x1005b0337 in copy (git_backup)
        return self.hash_map.allocator.dupe(u8, value);
                                           ^
/Volumes/zig/zig-aarch64-macos-0.14.1/lib/std/process.zig:164:45: 0x1005b05eb in put (git_backup)
            get_or_put.key_ptr.* = self.copy(key) catch |err| {
                                            ^
/Volumes/zig/zig-aarch64-macos-0.14.1/lib/std/process.zig:361:27: 0x1005b15e3 in getEnvMap (git_backup)
            try result.put(key, value);
                          ^
/Volumes/tt/git_backup.zig:46:44: 0x1005b0ca7 in encrypt_bundle (git_backup)
    var current = try std.process.getEnvMap(allocator);
                                           ^
/Volumes/tt/git_backup.zig:26:32: 0x1005b1db7 in main (git_backup)
        if (!try encrypt_bundle(dir, item.name, last_commit_date, allocator)) {
                               ^
/Volumes/zig/zig-aarch64-macos-0.14.1/lib/std/start.zig:660:37: 0x1005b2803 in main (git_backup)
            const result = root.main() catch |err| {
                                    ^
???:?:?: 0x1958e6b97 in ??? (???)
???:?:?: 0x0 in ??? (???)
```

This could be user error on my part, but I figured I should at least mention it here in case anyone else is searching for the same thing.
