### ISSUE TITLE
Building on Windows with VS2017

### ISSUE THREAD

**Issue by Sahnvour** [zig-lang/zig#850]
I'd like to build Zig using up uptodate visual studio. In order to do this I assume I would have to build llvm+clang myself with the same compiler.
Could you provide information on what targets are needed for zig, etc ?

**Comment by andrewrk** [comment]
you can follow these instructions, replacing 2015 with 2017. https://github.com/zig-lang/zig/wiki/How-to-build-LLVM%2C-libclang%2C-and-liblld-from-source

**Comment by Sahnvour** [comment]
How did I miss that page ... Thanks!

**Comment by andrewrk** [comment]
Also if you just want a working zig binary, you can download [appveyor artifacts](https://ci.appveyor.com/project/andrewrk/zig-d3l86/history?branch=master). Pick a green build, click "artifacts" and download the .zip file.

**Comment by andrewrk** [comment]
Feel free to comment here if you run into an issue and I'll re-open.
