### ISSUE TITLE
Zig standalone is very fast, but shared library is very slow

### ISSUE THREAD

**Issue by octonion** [zig-lang/zig#862]
I've written this sample program:

https://github.com/octonion/puzzles/blob/master/blackjack/zig

Compiled via ```zig build-exe --release-fast outcomes.zig``` and it's as fast as C. However, this version of the partitions function built as a shared library and called via Python is very slow:

https://github.com/octonion/puzzles/tree/master/blackjack/python-zig

I'm building the shared library via ```zig build-lib --release-fast partitions.zig --name libpartitions.so --library c```. It should run in about 0.06 seconds on my workstation (which is about how fast the shared library version run when called by Python for Ada, C, Fortran etc.), but runs on the order of 5 seconds.

**Comment by bnoordhuis** [comment]
Where is your python code calling into the shared library?

**Comment by octonion** [comment]
This is my mistake - please close this issue as I have committed the wrong code for Python calling Zig. That'll teach me to write code at 4 am.

**Comment by octonion** [comment]
I've committed the correct code. Performance when calling Zig from Python is exactly as expected, so this was a goof on my part.

https://github.com/octonion/puzzles/tree/master/blackjack/python-zig
