### ISSUE TITLE
example/guess_number issues

### ISSUE THREAD

**Issue by pr0g** [zig-lang/zig#882]
Hey there,

First time using zig so apologies if I've missed something. I thought I should mention this though as this is likely an area where a lot of newcomers to the language will go first.

I'm on Windows and am building using the latest zig release (zig-win64-0.2.0).

I tried to build and run the guess_number example project but ran into a few issues. First is the current sample fails to compile (it's likely a little out of date given the latest release) I fixed this without too much bother...

![image](https://user-images.githubusercontent.com/1136625/38193851-21e01354-366c-11e8-9ac9-780f4d4f5f96.png)

The next problem seems to be related to `stdin_file.read(line_buf[0..])` - when attempting to enter a guess, the application still waits for input after the first guess:

![image](https://user-images.githubusercontent.com/1136625/38194025-0659e906-366d-11e8-9881-1be75e453611.png)

After hitting return a few more times I get back to the prompt again:

![image](https://user-images.githubusercontent.com/1136625/38194060-2c413246-366d-11e8-97ef-c52e085ac08c.png)

I wanted to write some simple applications to learn zig that request input but can't seem to at the moment due to this issue. If there's something I'm doing wrong please let me know! :)

Thanks for your time!

Tom

**Comment by tiehuis** [comment]
Thanks for the report!

I can reproduce this on Linux, too. Doesn't seem like `read` is being terminated on `\n`. I don't have time right this moment, but will be fixed shortly.

**Comment by pr0g** [comment]
No problem! Ah, I see, thanks for the info :)

No rush at all, I can get back to noodling around with zig later :)

Cheers!

**Comment by andrewrk** [comment]
This is actually a slightly more complicated problem if you consider cross platform support.

The current implementation works on all platforms and does not use any terminal escape codes, but you have to enter the EOF into the stream (by pressing Ctrl+D twice instead of newline)

This is obviously a sub-par user experience, but to solve it, a full readline-esque solution is needed.

I think the next step is reading 1 byte at a time from stdin and ending the input on newline. But that prevents backspace from working. After that we have to implement a whole readline interface.

**Comment by pr0g** [comment]
Hey there,

I just attempted running guess_number again, this time pressing Ctrl+D twice before hitting return but I got the same issue. Maybe this is different on *nix? Is there a workaround you might suggest?

Thanks!


Tom

**Comment by andrewrk** [comment]
Hi @pr0g. I just pushed an improvement to the guess number example. Would you try the new code and see if this is a better experience? (don't forget to `make install`)

**Comment by pr0g** [comment]
Hi @andrewrk - I just grabbed the latest build off AppVeyor with your change (std.io readLine function) and pulled the latest changes from the zig repo. I recompiled the guessing_game example but unfortunately, I now get a different problem where no number is accepted:

![image](https://user-images.githubusercontent.com/1136625/38203747-29549e08-3698-11e8-8bd3-ef20b3a0077c.png)

Is the input not being parsed as a number? I haven't looked closely at the code yet to see what might be wrong.

Thanks for looking into this,

Cheers!

**Comment by andrewrk** [comment]
I'll have to try this on my windows laptop tonight. Thanks for testing!

**Comment by pr0g** [comment]
Sounds good! Not at all, 😄 I hope it was some help! Thanks!

**Comment by pr0g** [comment]
A small aside, I was able to build from source on Windows and thought I'd mention a useful cmake command - instead of using `msbuild` directly you can use `cmake --build`, so for building zig I used:

`cmake --build . --config Release --target INSTALL`

The nice thing about this is you don't have to launch the native tools command prompt. I use cmder (http://cmder.net/) on Windows which is much nicer than the standard cmd prompt.

The other thing is with the cmake generate command, you can use `-TLLVM-vs2014` to build with clang on Windows - to test this I used both...

(clang) `cmake .. -G "Visual Studio 15 2017 Win64" -TLLVM-vs2014 -DCMAKE_INSTALL_PREFIX=path\to\zig\build -DCMAKE_PREFIX_PATH="path\to\llvm+clang-6.0.0-win64-msvc-release" -DCMAKE_BUILD_TYPE=Release`

and

(msvc) `cmake .. -G "Visual Studio 15 2017 Win64" -Thost=x64 -DCMAKE_INSTALL_PREFIX=path\to\zig\build -DCMAKE_PREFIX_PATH="path\to\zig\llvm+clang-6.0.0-win64-msvc-release" -DCMAKE_BUILD_TYPE=Release`

Both compiled fine 😄 But did get the same behaviour I described before.

Cheers!
