### ISSUE TITLE
[question] Different output but should be the same?

### ISSUE THREAD

**Issue by molnarmark** [zig-lang/zig#886]
So I was playing around with zig, and came across this:
```
const fmt = @import("std").fmt;
const std = @import("std");
const assert = @import("std").debug.assert;
const mem = @import("std").mem;

fn reset() []const u8 {
  return "\x1b[0m";
}

pub fn fgRed(text:  []const u8) ![] u8 {
  var concat: [100]u8 = undefined;
  var resetCode = reset();
  return fmt.bufPrint(concat[0..], "{}{}{}\n", "\x1b[31;1m", text, resetCode);
}

pub fn main() !void {
    var stdout_file = try std.io.getStdOut();
    const colored = try fgRed("hi");
    try stdout_file.write(colored);
}
```

This code snippet produces the following:
```
m
```

However, doing this:
```
const fmt = @import("std").fmt;
const std = @import("std");
const assert = @import("std").debug.assert;
const mem = @import("std").mem;

fn reset() []const u8 {
  return "\x1b[0m";
}

pub fn fgRed(text:  []const u8) ![] u8 {
  var concat: [100]u8 = undefined;
  var resetCode = reset();
  return fmt.bufPrint(concat[0..], "{}{}{}\n", "\x1b[31;1m", text, reset());
}

pub fn main() !void {
    var stdout_file = try std.io.getStdOut();
    const colored = try fgRed("hi");
    try stdout_file.write(colored);
}
```
produces this:
```
▒▒▒% 
```

And this:
```
const fmt = @import("std").fmt;
const std = @import("std");
const assert = @import("std").debug.assert;
const mem = @import("std").mem;

fn reset() []const u8 {
  return "\x1b[0m";
}

pub fn fgRed(text:  []const u8) ![] u8 {
  var concat: [100]u8 = undefined;
  return fmt.bufPrint(concat[0..], "{}{}{}\n", "\x1b[31;1m", text, reset());
}

pub fn main() !void {
    var stdout_file = try std.io.getStdOut();
    const colored = try fgRed("hi");
    try stdout_file.write(colored);
}
```
Produces this:
```
;1mhi
```

I believe the output should be the same on all 3 of these versions, but I might be missing something. If I am, I'd love an explanation.

Thank you.

**Comment by andrewrk** [comment]
When we have more advanced semantic analysis you would get a compile error for this code.

`  return fmt.bufPrint(concat[0..], "{}{}{}\n", "\x1b[31;1m", text, reset());`

This is returning a pointer to stack-allocated data from a function, which is a dangling pointer. You have invoked undefined behavior for which we have not come up with runtime safety detection.

Try running your code with valgrind.

**Comment by molnarmark** [comment]
If I understand correctly, `reset()` is returning a pointer?

**Comment by andrewrk** [comment]
Reset is returning a ptr and a len of statically allocated data, which is valid for the entire duration of the program. On the other hand:

`var concat: [100]u8 = undefined;`

`concat` is valid for the duration of the `fgRed` function call.

In order to concatenate arrays, you are limited to these choices:

 * concatenate compile-time known data
 * allocate memory on the stack (your choice above), and then only use the concatenated data in the function call where the stack data is valid (you have not done this above)
 * allocate memory on the heap for the result of the concatenation, and then free the memory later.
 * instead of concatenating, write the prefix directly, then write the payload directly, then write the suffix directly.

**Comment by molnarmark** [comment]
I've changed it around to do this:
```
pub fn fgRed(text:  []const u8) []const u8 {
  return "\x1b[31;1m" ++ text;
}
``` 
but since text is a const, it cant evaluate it, and I cant pass it as a non-const because I'd be limited to a fixed length.
Casting from []const u8 to [] u8 is also forbidden for obvious reasons. Is there a way around this?

Sorry about the ton of questions. 😄

**Comment by rdlph** [comment]
I don't know if you are OK with using allocators for this, but the way I would do this is to just use std.Buffer like this:

```
const std = @import("std");
const warn = std.debug.warn;


const RESET  = "\x1B[0m";
const FG_RED ="\x1B[31;1m";


pub fn redText(text: []const u8, buf: &std.Buffer) ![]const u8 {
    const str_offset = buf.len();

    try buf.append(FG_RED);
    try buf.append(text);
    try buf.append(RESET);
    
    const bufslice = buf.toSliceConst();
    return bufslice[str_offset..buf.len()];
}

test "example" {
    var allocp = std.debug.global_allocator;
    var buf = try std.Buffer.init(allocp,"");

    const str  = try redText("hello",&buf);
    const str2 = try redText("world",&buf);

    warn("\n{} {}!\n",str,str2);
    buf.deinit();
}
```

It both lets you return slices to the individual strings, but also lets you build up string in the buffer so you don't have to concatenate them later. If you just stick to append operations, you can treat it something like an ArenaAllocator for the `[]const u8`s that your ansi coloring functions return, and deallocate them all in one go when you are done with them with `Buffer.deinit()`.

**Comment by andrewrk** [comment]
Iterating on @rdlph's code:

```zig
test "example" {
    var allocp = std.debug.global_allocator;
    var buf = try std.Buffer.init(allocp,"");
    defer buf.deinit();

    const str  = try redText("hello",&buf);
    const str2 = try redText("world",&buf);

    warn("\n{} {}!\n",str,str2);
}
```

This couples the init and deinit code.

**Comment by andrewrk** [comment]
I think an even better way to do it however is this:

```zig
const std = @import("std");
const warn = std.debug.warn;
const RESET  = "\x1B[0m";
const FG_RED ="\x1B[31;1m";

test "example" {
    const str = "hello";
    const str2 = "world";
    warn("{} " ++ FG_RED ++ "{}\n" ++ RESET, str, str2);
}
```

**Comment by molnarmark** [comment]
Thanks for the help! It makes sense now.
