### ISSUE TITLE
Bug: Hashmap Equality Comparer Incorrect Type

### ISSUE THREAD

**Issue by BraedonWooding** [zig-lang/zig#887]
The hash_map equality comparer function should be of type 'fn([]const u8, []const u8)' as that is convertible implicitly from '[]u8', where as '[]const u8' is not convertible to '[]u8' this means for example when I was implementing a string to struct hash-map (for a JSON library, for the 'map' type) I have to currently have two string comparison functions one for my day to day comparisons (since for example I compare two strings such as if a set of tokens equals "false" for example) in format '[]const u8, []const u8' and another just for hash_map.  

Furthermore if I have a set of string functions that most standard libraries have (like `is_whitespace(u8)`, or `hash_code_string` for example), would I have to open an issue with all them detailed out or just a PR since their implementations are stock standard?

**Comment by bnoordhuis** [comment]
Correct me if I'm wrong but wouldn't you normally use `[]const u8` for the key type?  Keys are supposed to be immutable.  You can use `mem.eql_slice_u8()` when they're `[]const u8`.

> `is_whitespace(u8)`

Could be tricky.  Whitespace is locale-dependent and locale is an issue that zig's std has sidestepped so far.

> `hash_code_string`

Already exists in the form of `mem.hash_slice_u8()`, or do I misunderstand?

You're welcome to open a pull request, of course.  We can discuss the details there.

**Comment by BraedonWooding** [comment]
Yeh you could, I actually stuffed up in my mindset when I initially did it and only now have fixed it, however I guess I still hold the belief that the key should be forced to be constant through some kind of 'attribute'.  

I'm approaching the language to try and see where I trip up to see where I think the language needs to 'evolve' one of the major things is around const/non-const and their interactions, it isn't always very clear and there isn't a magical 'const' remover like in C++ for when you stuff up meaning you often have to go back and edit and possibly restructure code to fix it.

Whitespace isn't particularly locale independent (not in any real meaningful way as in there are only a few locales that actually matter), I would be looking towards implementing a proper locale system though :), I just finished ZigJSON and I want to just play around a bit more but I do really like the language so far +/- a few things.

Yes it does exist there, though I would argue that is a weird place for it to exist, the standard library suffers from not having good documentation (which is why I didn't find it in the first place), and a weird structure in some cases but is overall quite good.  Perhaps something like an XML style comment system (or even JSON especially since I just finished the parser haha) and using a 'doxygen' like reader on it :) to produce some HTML.

Regardless I'm going to add a few string utilities tonight just as a step into the project and please do discuss stuff like locales but I'll aim to avoid them for now since I'm sure there is much discussion people will wish to have on how it is to be done.

I'm gonna close this for now though since it isn't really a bug.
