### ISSUE TITLE
Bug: Casting From []const u8 to []u8 doesn't work for functions but other types do

### ISSUE THREAD

**Issue by BraedonWooding** [zig-lang/zig#889]
Code example to explain
```C
fn A(array: []const i32, b: []const i32)bool {
    // ... Code here
    return true;
}

fn B(array: []const u8, other: []const u8)bool {
    /// ... Code here
    return true;
}

fn foo(comptime T: type, func: fn(array: T, other: T)bool, array: T) void {
    _ = func(array, array);
}

test "Test" {
    var array = []i32 { 0, 1, 2};
    // This will compile file, notice how A takes constants
    // But this is obviously cast-able to just non-constants
    foo([]i32, A, array[0..]);
    var str = "BOOOO";
    // This line won't compile however
    foo([]u8, B, str);
}
```

From looking at the compiler code this is due to perhaps how it handles the special cause of []u8's cast-abilities being a conflict with other how other types cast.  I'm thinking its a missing case here `ir_types_match_with_implicit_cast(...)`.

**Comment by BraedonWooding** [comment]
Ahhh I think you have misunderstood, the array/slice in both cases aren't mutable they are a literal.  The problem is the fact that it works for the integer version but not for the string version.  If you have the string like `var str = []u8 { 'B', 'O'.... }` it still won't work.

You can make it convert to a slice then it works, but I see an inconsistency, why is it that it doesn't work just for u8 but for all other primitives it works?  Now that could be a bug with the other primitives doing a wrong implicit cast or with u8 I don't know.  But a bug regardless?

Since shouldn't you also have to write `foo([]i32, A, array[0..])` or use a const, but not necessarily in this case it seems?

**Comment by Hejsil** [comment]
@BraedonWooding I think you should look at your code example again :)
```
...
    foo([]i32, A, array[0..]);
...
    foo([]u8, B, str);
...
```

You are slicing `array`, and that is why it works

**Comment by BraedonWooding** [comment]
Oh my... Wow I feel stupid.  Legitimately have been trying to figure out why for ages, my subconscious wrote it right once haha.  Closing cause of my stupidity haha.
