### ISSUE TITLE
A place to put zig projects?

### ISSUE THREAD

**Issue by BraedonWooding** [zig-lang/zig#892]
For example I just finished JSON in zig ([here](https://github.com/BraedonWooding/ZigJSON/tree/master)), I think we should put up a place to list a few major projects (which I guess right now includes basically all of them) since it would help others to see some nifty code and examples :), kinda like the Examples.md that currently exists.

**Comment by Hejsil** [comment]
There is the "Zig in the Wild" section on the [website](https://ziglang.org/) :)
