### ISSUE TITLE
Bug: Unable To Inline Function

### ISSUE THREAD

**Issue by BraedonWooding** [zig-lang/zig#916]
Perhaps related to #913 
Error Log:
```
./zig test /Users/Braedon/zig/test/behavior.zig --target-arch x86_64 --target-os linux --target-environ gnu --test-name-prefix behavior-linux-x86_64-Debug-bare  
/Users/Braedon/zig/test/cases/fn.zig:113:8: error: unable to inline function
inline fn inlineFn() void { }
       ^
```
Done on MacOS Air, High Sierra Latest Version.  This was tested on the main upstream master branch without ANY changes applied :).

**Comment by andrewrk** [comment]
Fixed in 1999f0daad505f414f97845ecde0a56b3c2fedfd. It was a bug introduced a long time ago, brought to light by the new inline fn test.
