### ISSUE TITLE
Fixing up Directory/File

### ISSUE THREAD

**Issue by BraedonWooding** [zig-lang/zig#926]
> Edited for clarification :).

Directory/File/Index/Path is objectively a mess it has functions in places where they shouldn't be, FIle.zig has the File struct however Directory struct is stored in Path.zig.  There are functions that just determine which call to make, overall this leads to quite annoying code to follow as it is all in the same place.  The way I'm currently changing it too is the way the majority of the code is currently in, that each os gets its own folder and its own files to handle IO/Pathing and so on, then they are just merged in to the path.zig/index.zig files through a mixture of an initial `if (is_windows)` call and `use` :).

## Motivation

I was going to add a few more functions like combining paths and `isDir` and stuff like that because I was building a package manager and found it hell without some nice directory tools, but it really just feels meh to do it because its a complete mess, it takes forever to traverse the code and the file is just bloated.

**Comment by thejoshwolfe** [comment]
There's an awful lot of "moving code around" in this description. It's easier to review PR's if refactoring, such as moving code around, is kept separate from any meaningful code change. Please do the refactoring in its own PR, and also please contribute meaningful changes before submitting any refactoring PR's. Meaningful changes are far more valuable than refactoring changes, and refactoring can easily become a bikeshedding edit war. Contribute meaningful changes first to give yourself leverage to argue for your refactoring preferences.

To clarify what I mean by meaningful changes: enable the user to accomplish something that wasn't possible before without them writing their own well-defined utilities. Generally contribute new functions before modifying existing ones.

And I'd also like to give my standard for what makes an API worth having (I would like everyone on the Zig team and everywhere else to adopt this standard, but for now I call it "my standard"): Write software in order of end-user facing first, then general utilities to support that end-user facing software. This means don't write general software unless real actual code wants to use it.

Specifically in this issue, you mention "add multiple paths together". That's common enough that it should be easy to make specific software that wants to do that. Please describe or link to your software that wants to do that before/while contributing general utilities that enable that functionality. And again I'm talking about real actual software, not some abstract hypothetical software that *would* want the functionality.

**Comment by thejoshwolfe** [comment]
Have you written any application code in Zig? Do you want to write any application code in Zig? If yes to either, please describe or link to the application.

**Comment by BraedonWooding** [comment]
How does that have ANY relevance whatsoever, furthermore all the application code I've written are mostly around playing around with Zig I have some links under my github for ZigJSON here for example [ZigJSON](https://github.com/BraedonWooding/ZigJSON).  I would not count Zig to be near production code despite this however I quite enjoy coding in it; currently I have also worked on various other things such as a package manager, a DOML parser (a language I designed similar to the goals of JSON but is faster and is more like a scripting language), a few simple games such as snake, tic tac toe and others.  Only ZigJSON is on my github since I generally don't release things there until I'm either happy with them or its been a few years and I have stopped dev on a project :).

But I struggle to see how this has any to all relevance, please further elaborate, however when I tried to implement a package manager the extreme annoyance of Zig's lack of proper handling of files was the main motivation of me doing this however it was then the annoyance of the inconsistency of the std that made me want to go in and fix it :).

Once more this question is irrelevant to the discussion and I hope is purely based on a personal interest rather than other means...

**Comment by thejoshwolfe** [comment]
Ok that helps me understand the motivation for this issue. (And those  projects seem really cool, and I'd like to know more about them sometime.)

> such as `isDir()`

Yeah, I think that function is missing from the std library. [I ran into a desire for that as well](https://github.com/thejoshwolfe/hexdump-zip/blob/61759bc428d0b4f532418abf77b0c6374e710a3d/src/hexdump-zip.zig#L210). That would be a great addition.

> when you want to add multiple paths together it gets a little annoying

String concatenation is generally hard in Zig compared to other languages because of potential out-of-memory situations.

> (like we should probably just store a comptime array of ptrs to strings and then when iterating you can just smoosh them together perhaps).

I don't understand this suggestion. How does a comptime array help us with runtime values?

> `use osPath = if (windows) Windows.Path else Posix.Path`

If the Path implementations are completely separate, it will be tricky to share code between them. The current strategy of branching on OS at the last minute facilitates as much reuse between OSes as possible. However, I see the appeal in having complete coherent implementations for each OS.

I think it's not clear what's the best way to organize OS-specific path code. There are arguments on both sides. Another argument counter to your strategy is that you can write the same test for all OSes at once in the same file next to the implementation(s) of the function. e.g. [here](https://github.com/zig-lang/zig/blob/96ebd8b23b39e2d4019a8019a6774d7c3d20149d/std/os/path.zig#L838).

**Comment by BraedonWooding** [comment]
> I don't understand this suggestion. How does a comptime array help us with runtime values?

A compile time array of slices as in the length is compile time decided but the content is still runtime :), this means that if you did `AddPaths("a/b/c", "d/e")` you would get an array that looked something like; `pathPtr: [2]&[]const u8` that is an array of pointers to each of the paths.  This stops any allocations from occurring, however a downside is that you need to maintain all the original paths and if they go out of scope we get problems however I don't think this is really a problem since if they do Zig will give you a nice enough error, indicating you need to fix your scoping :).

> Another argument counter to your strategy is that you can write the same test for all OSes at once in the same file next to the implementation(s) of the function

However a negative of this is that you only need to test each of the OS's you don't need to test the composition function as well that'll just bind to one of the OS's.  So with that in mind you can attach each of the individual OS tests next to the OS function in its own implementation meaning that you put it next to what actually is being called.  I wouldn't call this a counter argument due to this reason.

Keep in mind that the implementations can be different HOWEVER there is a universal API that must be followed i.e. every OS must have an `open` function under its own `io.zig` and each one would need a `basename` function under its own `path.zig` and so on.  The benefits of this is that if it doesn't you get an error indicating that no such function exists which is basically a perfect error, though of course we could have some compile time code that just performs reflection and produces nicer compiler errors if they are viewed as bad.

Basically I view it as this; currently with only two implementations the code is only well twice as long, as our 'n' increases to support perhaps different os's for example Zen, and maybe FreeBSD or whatever this means that our code will then triple, then quadruple and so on.  Thus meaning our path file could easily be up to 2-3k lines and our index.zig file is already at 2.5k lines though it wouldn't be affected so harshly but atleast half of those lines would be effected by this growth factor.

This is currently what my branch looks [like](https://github.com/BraedonWooding/zig/tree/NicerFileUtils/std/os).  I've only down path.zig currently.  My changes however has brought it down to ONLY 400 lines, yes ONLY 400 lines.  And I've almost brought index.zig down by around 800 lines and I'm not even done with it yet.

Of course these lines are offset'ed into the individual OS files however most files are under or around 500 lines in each OS meaning that they are very readable.

I guess that's the entirety of the argument on 'my side'.

**Comment by andrewrk** [comment]
We'll clean up the stdlib API as part of the full stdlib audit before 1.0.0.   For now, let's make improvements and additions and eventually we'll have all the implementations we want for 1.0.0, and we can proceed to do a final organization pass. 

I need a more concrete proposal to accept, or a PR.

**Comment by BraedonWooding** [comment]
I've got a copy that I'm just doing work on overtime as I need certain things, I'll create a PR when I think it is ready for the world to see.
