### ISSUE TITLE
--msvc-lib-dir, --kernel32-lib-dir ignored on windows

### ISSUE THREAD

**Issue by tgschultz** [zig-lang/zig#927]
```
zig build-exe thing.zig --msvc-lib-dir "e:\VC\BuildTools\lib\x64\" --kernel32-lib-dir "e:\VC\BuildTools\umlib\x64\"
```
```
Unable to determine vcruntime path.
```

I have verified the paths are correct and that kernel32.lib and vcruntime.lib are in their respective locations. 

Using process monitor I find that Zig does not even attempt to access these paths, instead checking the following registry keys immediately after building the obj:
```
HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows Kits\Installed Roots\KitsRoot10
HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows Kits\Installed Roots\KitsRoot81
```
Which do not exist. It then proceeds to crash.

**Comment by andrewrk** [comment]
I believe this is a regression from #872.
