### ISSUE TITLE
Zig now available in TIO online sandbox

### ISSUE THREAD

**Issue by turbo** [zig-lang/zig#937]
[Try It Online](https://tio.run/#) today added Zig 0.2, which means one can try Zig online without downloading or installing anything, here: https://tio.run/#zig

**Comment by andrewchambers** [comment]
What's the process for keeping the version up to date?

**Comment by turbo** [comment]
Open an issue here if you want the version bumped: https://github.com/TryItOnline/tryitonline

**Comment by andrewrk** [comment]
Thanks for letting me know! I'll re-open this and then close it once I update ziglang.org with a link.

**Comment by andrewrk** [comment]
Alright I have put a link on ziglang.org
