### ISSUE TITLE
Unreachable condition in compiler

### ISSUE THREAD

**Issue by hryx** [zig-lang/zig#945]
Here is a short program which causes the compiler to output "unreachable" and be killed with SIGABRT:

https://gist.github.com/hryx/c274aa28ed7a03e189203354b1b32fa4

The program itself is probably invalid, but I was told this may still be a compiler bug.

My setup: macOS 10.12.6, zig 0.2.0 (via Homebrew), fish 2.7.1. I ran `zig build-exe main.zig`.

**Comment by BraedonWooding** [comment]
Good find it is a bug :).

I get the following error message when doing on latest master;
```
Assertion failed: (target_value_ptr->value.type->id == TypeTableEntryIdPointer), function ir_analyze_instruction_switch_target, file /.../Zig/src/ir.cpp, line 14785.
Abort trap: 6
```

Assertions mean compiler bugs.
