### ISSUE TITLE
Wraparound +% not for literals?

### ISSUE THREAD

**Issue by PavelVozenilek** [zig-lang/zig#964]
I try this in online tool:

```
const std = @import("std");
const warn = std.debug.warn;

pub fn main() void {

  const o : u8 = 200 +% 200;
  warn("{}\n", o);    
}

```
and it gives me error:

`/home/runner/.code.tio:6:22: error: integer value 400 cannot be implicitly casted to type 'u8'
`

I expected wraparounds to work at compile time too.

**Comment by andrewrk** [comment]
comptime integers never wrap. They have unlimited bits. You need to cast your literals to a specific number of bits before doing a wraparound operation.

**Comment by PavelVozenilek** [comment]
Contrary to previous example, where intent was clear, this compiles:


```
pub fn main() void {

  const o = 200 +% 200;
}

```

IMHO it should not. It is not clear what the programmer wanted.

**Comment by PavelVozenilek** [comment]
@andrewrk 

This compiles and produces correct result:

```
const std = @import("std");
const warn = std.debug.warn;

pub fn main() void {

  const o : u8 = u8(200) +% u8(200);
  warn("{}\n", o);    
}

```
But it feels as superfluous, to cast everything when there is no ambiguity.
