### ISSUE TITLE
String Interpolation

### ISSUE THREAD

**Issue by BraedonWooding** [zig-lang/zig#968]
I couldn't find any issue that matched this, so I felt this should be created.

Most languages have a nicer way to do a format then having to do something like `format("{}", myObj)`, often they either take the 'Swift' route and do something like `"\{myObj}"` with the `\{`being existent in all strings; I personally don't like this as it does seem to do 'stuff' behind your back without you asking for it.

Whereas the 'C#' way which is something like `$"{MyObj}"`, requires a symbol to designate that it is interpolated, I feel that this way is nicer in terms of usability and demonstrates clearly if a string should be interpolated you can write '{' by double writing it like `{{` kinda like escaping it; we could also allow escaping it via the typical escape keyword `\{` but that may be too similar to the first method to confuse people.

The third way is I guess more inline with the fact that Zig doesn't really use symbols for things like this and uses 'words' (i.e. transition from `%` to `try`) so I guess it would be something like `fmt "{MyObj}"` which would just translate to `format("{}", MyObj)`.

> 'fmt' is just a name I chose to demonstrate the idea it is an implementation detail so probably not something to 'argue' about, more focus on the idea.

## Why have this?

It helps when you have long format strings as you can easily prevent weird bugs of putting things in wrong orders (though those bugs are typically caught easily).  I don't have too many reasons for why they really are 'needed' so I wouldn't say that this is a necessity but it's one of those things I find that most people just go 'huh that's nice', kinda like how the 'for' loop in zig is not necessary but it just makes things nice.

On the other hand the negative of having it is 'bloating the language' (something I disagree that this would do but I can understand this view), you could also argue it is doing stuff 'behind' your back, but I would argue it is not doing anymore than what something like 'try' is using.

😄

**Comment by Hejsil** [comment]
One other note! Did not think about only allowing this at `comptime`. Here we don't have to worry about allocation failure and all that stuff, and we already have `++` and `**`. I think this feature have a higher chance of being a `comptime` only thing, but I still don't really think it's need.

**Comment by BraedonWooding** [comment]
Been meaning to reply, just passed my thoughts :).  I actually completely agree, and I don't really see this in 'Zig' the more I think about it; however I still felt it was worth creating the issue just incase others had opinions :).  Also means its a place to drive people who ask this in the future.

On your other points, I agree that referring to objects is quite nice; printing different format strings at runtime is extremely important too, though I think that is probably the place for a library to come in?  Since it is quite a niche place, however I may be wrong.

And yes it was a complete comptime feature so that's why I didn't mention allocators :).  But I actually don't think it's a need or even a want really, I think Zig is nice enough already with printing things.

**Comment by andrewrk** [comment]
:+1:
