### ISSUE TITLE
comptime type deduction

### ISSUE THREAD

**Issue by bheads** [zig-lang/zig#984]
It seems like this might become a common pattern for generic coding in zig

```zig
pub fn foo(comptime T: type, T: a) void {
}

var a  = 5;
foo(int, a); 
```
In these cases the compiler knows the type of a, it would be useful if you did not have to supply the type. 

```zig
foo(a);  //<< much simpler and cleaner
```

Maybe some reorganization of the function signature.  

```zig
pub fn foo(T: a, comptime T: type = @typeOf(a)) void  {..}
```

**Comment by bheads** [comment]
I have not seen that yet, should cover a lot of cases.  But what about enforcing same types

```
pub fn foo(comptime T: type, a : T, b : T)
```

Would have to include a typeof check in the body

**Comment by andrewrk** [comment]
That can work like this:

```zig
fn foo(a: var, b: @typeOf(a)) void {}
```

However perhaps you want to resolve the types with peer type resolution. There's an open issue for that: #439

**Comment by bheads** [comment]
Good to know typeOf works likes this.  Thanks.
